### ISSUE TITLE
Modrinth App always installs primary jar even if other is selected

### ISSUE THREAD

**Issue by wlad26** [modrinth/theseus#1014]
### Describe the bug

Modrinth App always installs primary jar even if other is selected
This project version (https://modrinth.com/mod/easylan/version/3PBoN5QH) has two jars,
one is primary/featured (for 1.19.4) and the other is for 1.19.2
![image](https://github.com/modrinth/theseus/assets/65756919/9c056769-2c58-42f5-8a2d-28e3fb92f9aa)

So, Modrinth App always installs the primary jar even if I select 1.19.2 jar
You can also go to site and check that you can download 1.19.2 version normally, so it's Theseus problem

Edited: thanks to Effigy from Discord for this report!
### Steps to reproduce

1. Create any non-vanilla instance
2. Click Add content
3. You can use 'Override game versions' and 'Override loaders' checkboxes for optimal searching through all the mods
4. Open a mod which has a version with multiple jars
5. Open this version
6. Try to install non-primary jar
7. Open your instance folder and go to Mods folder
8. You can see that primary jar of uploaded version was installed instead of what you selected

### Expected behavior

Modrinth App always installs an jar which has been selected by user

### System information

Windows 11 23H2 22635.3061 (Beta channel)
Theseus v0.6.3

**Comment by triphora** [comment]
This is not a supported use case, the author has done this improperly. Please file a site report.
