### ISSUE TITLE
Mod update issues

### ISSUE THREAD

**Issue by DSLZL** [modrinth/theseus#1045]
### Describe the bug

For some reasons, there is no update prompt and no change in the button in an instance page, but there is an updated version when you click in.
An example is Iris Shaders, which is still 1.6.14 on my 1.20.4 release, but has been updated to 1.6.17 and the author has indicated support for 1.20.4, why can't it be updated? Instead, it is to be replaced manually

**Comment by Imajo24I** [comment]
"The version file hash update route (/v2/version_files/update) will temporarily replicate the behavior of /v2/version_files (and therefore behave as if no mods have updates). We are fixing some performance issues with this route. It will be back up soon!" (From Modrinth Discord)

**Comment by DSLZL** [comment]
> "The version file hash update route (/v2/version_files/update) will temporarily replicate the behavior of /v2/version_files (and therefore behave as if no mods have updates). We are fixing some performance issues with this route. It will be back up soon!" (From Modrinth Discord)“版本文件哈希更新路由 （/v2/version_files/update） 将暂时复制 /v2/version_files 的行为（因此表现得好像没有 mod 有更新）。我们正在修复此路由的一些性能问题。它很快就会回来！（来自 Modrinth Discord）

Thanks
