### ISSUE TITLE
Add Java 21 to Java settings

### ISSUE THREAD

**Issue by ubionexd** [modrinth/theseus#1099]
### Is your suggested enhancement related to a problem? Please describe.

A new snapshot just came out that requires Java 21
https://quiltmc.org/en/mc-patchnotes/#24w14a

**Comment by bangetto** [comment]
1.20.5 now in pre-release so this important to be fixed!

**Comment by theoparis** [comment]
I would also like the ability to use JDK 22 from my system - maybe it would be better to have a Java 8 vs Newer Java rather than a java 8 vs java 17 vs java 21 vs java 21 option...

**Comment by ubionexd** [comment]
I think a toggle between system and app JDK would be better, so you still have the ability to install the JDK 8/17/21 from the app.
