### ISSUE TITLE
Don't use Discord's CDN to serve images

### ISSUE THREAD

**Issue by getchoo** [modrinth/theseus#1116]
### Describe the bug

https://github.com/modrinth/theseus/blob/3e7fd808248003cf87ced405ba7c1d536b596f97/theseus_gui/src/components/ui/tutorial/OnboardingScreen.vue#L114

This will eventually break completely, but seems to already in [plenty of situations](https://github.com/flathub/flathub/pull/4950#issuecomment-2040492564)

### Steps to reproduce

1. Use onboarding

### Expected behavior

Image appears

### System information

Linux with v0.6.3

### Additional context

This is not a flatpak specific bug and appears in all packagings. This is also more detrimental with newer versions of webkitgtk, where some ui buttons cannot be pressed due to the images not loading

**Comment by TheKodeToad** [comment]
I believe all attachment URLs expire now.

**Comment by Geometrically** [comment]
Fixed!
