### ISSUE TITLE
Locked out of my Modrinth account because of invalid credentials

### ISSUE THREAD

**Issue by Cod1ngGamer** [modrinth/theseus#1126]
### Describe the bug

Whenever I try to log in to my Modrinth account on modrinth.com, it gives me this error:
Authentication Error: Invalid Authentication Credentials
I'm not able to log into my account to edit my mods, so I need some way to fix this.

### Steps to reproduce

Just try to log in.

### Expected behavior

I should be able to log in.

### System information

Windows 11

**Comment by brawaru** [comment]
This is not a support website. Please contact support at https://support.modrinth.com instead.
