### ISSUE TITLE
Modpack saving as generic file

### ISSUE THREAD

**Issue by Dangerabbit** [modrinth/theseus#1162]
### Describe the bug

Whenever I save a mod pack it just saves a generic file instead
For example, if the mod pack I tried to save is called EXAMPLE then it would save as a file that is just EXAMPLE with no file type or data inside

### Steps to reproduce

1. Press Export mod pack
2. Press Export
3. Choose folder (for example downloads)
4. Press save
5. Go to folder
6. Find empty file

### Expected behavior

It should just save as a .mrpack file with data inside

### System information

Windows 11
Theseus v0.7.1

Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Comment by brawaru** [comment]
Your modpack likely has : in it, causing Windows to think Modrinth is trying to write to an alternative stream of that file.

**Comment by Dangerabbit** [comment]
Thanks! That was the problem!
