### ISSUE TITLE
Modrinth app crashing after opening logs

### ISSUE THREAD

**Issue by AngelBePro** [modrinth/theseus#1164]
### Describe the bug

Trying to view the logs of any mod pack freezes modrinth.

### Steps to reproduce

1. Go to any mod pack
2. In the left section, click on logs
3. App freezes entierly

### Expected behavior

Opening logs should not freeze the app for a long time, since when I try to see if it would unfreeze, it never does, and I have waited for minutes. Minutes isn't alot, but from a freeze i expect maximum of 2-5 sec freeze.

### System information

OS: Arch Linux x86_64
CPU: Intel i5-10400F (12) @ 4.300GHz
GPU: NVIDIA GeForce RTX 3070
Memory: 15887MiB
Theseus v0.7.1

### Additional context

When opening the logs, the logs section does appear to render, but the enitre app remains freezing, trying to close it with X button does not work and I have to use System Monitor to forcefully quit the app.

**Comment by DUDEbehindDUDE** [comment]
Same issue on Linux Mint 21.3 Cinnamon

**Comment by ImaDoor2785** [comment]
same on ubuntu 22 and 23

**Comment by CommanderGL** [comment]
same issue on archlinux (using AUR package)

**Comment by ImaDoor2785** [comment]
switching to wayland from x11 fixws it

**Comment by CommanderGL** [comment]
I am already on wayland

**Comment by quaap** [comment]
Same as Issue #1127 ?

**Comment by AngelBePro** [comment]
> Same as Issue #1127 ?

Yes it is.

**Comment by AngelBePro** [comment]
Duplicate issue #1127

**Comment by rassawyer** [comment]
I am getting similar, though not quite identical results. I have the slow scrolling issue, which seems to get worse that faster I try to scroll. 
I also have issues trying to access mod logs. The app freezes, briefly, then crashes, with the following error in console.
`/usr/bin/modrinth-app: line 2:  8134 Segmentation fault      (core dumped) env WEBKIT_DISABLE_DMABUF_RENDERER=1 /opt/modrinth-app/modrinth-app "$@"`

Potentially relevant system info:
`AMD Ryzen 7 PRO 6850U with Radeon Graphics`
`Operating System: Arch Linux
          Kernel: Linux 6.11.5-arch1-1`
