### ISSUE TITLE
Cannot create categories to add modpacks to

### ISSUE THREAD

**Issue by DovydasTEDS** [modrinth/theseus#1173]
### Describe the bug

I want to put a few modpacks in a category but I cannot.

### Steps to reproduce

Go to an instance's settings page.
Click the categories dropdown.

### Expected behavior

It should let me make categories.

### System information

Windows
v0.7.1

**Comment by ToBinio** [comment]
what exactly can you not do?

does nothing happen when you click on the dropdown?
or can you not type in it?
or does nothing happen when you press `Add new Category`?
does the category disappear after being added?
or something completely different?

**Comment by DovydasTEDS** [comment]
I didn't know I could type in it.
All good now.
