### ISSUE TITLE
Navigation Back button

### ISSUE THREAD

**Issue by glitch-infused** [modrinth/theseus#129]
### Is your suggested enhancement related to a problem? Please describe.

When browsing mods to install when you click on a mod this brings you to the mod's page. However when you want to continue browsing mods there is no back button, thus you have to return to the installations menu, click on the installation, click on browse again and scroll back to where you were.

Also using keyboard shortcuts like `alt+left arrow` does not work as you will be brought to the browsing page, but the app won't let you install mods for the installation you were working on

### Describe the solution you'd like

A back button in navigation that brings you back to the previous state.

**Comment by triphora** [comment]
Please report all bugs and suggestions with the alpha in the `#test-feedback` channel in Discord.
