### ISSUE TITLE
The UI is useless and unresponsive during downloading

### ISSUE THREAD

**Issue by MarkusTieger** [modrinth/theseus#140]
### Describe the bug

The GUI is useless and unresponsive during downloading.

### Steps to reproduce

1. Open the 'Modrinth App'
2. On the Sidebar click 'Browse'
3. Click on a Modpack (for example Fabulously Optimized)
4. Click 'Install'
5. You will see that the UI is unresponsive during the download

### Expected behavior

The download should be in the background and the UI should be usable while it's downloading.

### Additional context

Tested on Garuda Linux (Arch Linux based) using an [AUR-Package](https://aur.archlinux.org/packages/theseus-gui-git) which compiles and builds a package from this. Git Commit: e0e9c3f1666d3db220cd8918acfa091ec4eecb36

**Comment by triphora** [comment]
Support is currently not being provided for the app
