### ISSUE TITLE
Versions in "Filter Versions" dropdown do not show versions in chronological order

### ISSUE THREAD

**Issue by emmaLikesLinux** [modrinth/theseus#142]
### Describe the bug

The versions in the "Filter Versions" dropdown don't show versions in chronological order.

### Steps to reproduce

1. Go to "Browse" 
2. View anything on Modrinth with lots of versions (ex. Rethinking Voxels)
3. Go to "Versions"
4. Click on the Filter Versions dropdown.
5. Observe that versions are not in chronological order.

### Expected behavior

Versions are shown in chronological order, perhaps with snapshots at the bottom.

**Comment by Prospector** [comment]
Following your reproduction steps I could not reproduce. Could you include a screenshot of the issue?

![image](https://github.com/modrinth/theseus/assets/6166773/614433f4-f0ef-4043-9d1b-b99e992cecc2)

**Comment by emmaLikesLinux** [comment]
![](https://i.imgur.com/KwZCMOP.png)

**Comment by Prospector** [comment]
Oh, this is theseus. My bad. Feedback for the app is currently being collected on our Discord server

**Comment by emmaLikesLinux** [comment]
I don't know rust that much but would it be okay if I make a pull req with my proposed solution?

**Comment by emmaLikesLinux** [comment]
I fixed it and created a pull request, I'll mark as resolved
https://github.com/modrinth/theseus/pull/143
