### ISSUE TITLE
Options wrap weirdly on instance page

### ISSUE THREAD

**Issue by Prospector** [modrinth/theseus#152]
### Describe the bug

Options look weird when they wrap on instance menu. Ideally, if everything can't fit on one line, the options will move to the line below the chips and be left-aligned, but if there's room they fit snugly right-aligned next to the chips. Might be complicated to impl

![image](https://github.com/modrinth/theseus/assets/6166773/05897b5a-1ce6-4104-badc-b1f003761271)

**Comment by CodexAdrian** [comment]
Fixed in #325
