### ISSUE TITLE
Native windows title bar showing

### ISSUE THREAD

**Issue by zndrmn** [modrinth/theseus#158]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/77690119/02751ecf-b7ef-4740-811d-4f3d5f438872)

### Steps to reproduce

1. update to 0.2.0

### Expected behavior

bottom right example
![image](https://github.com/modrinth/theseus/assets/77690119/e9f59e0f-9499-413b-bc3c-c782d5146bd6)

**Comment by srnyx** [comment]
This only happens on first launch, subsequent launches are fine (at least for me)

**Comment by zndrmn** [comment]
I've tried restarting it and stuff, I'll try restarting my pc later

**Comment by Cheos137** [comment]
Happens on subsequent launches, too, for me (Windows 10)

**Comment by Goldsucher07** [comment]
Copy & paste from my Github issue and what I have tried:

- [ ]  Deleted the program manually (I don't know where it's located.)
- [x]  Uninstalled the program using the official uninstaller.
- [x]  Restarted the PC while the program was installed.
- [x]  Gave it another path while installing.

**Comment by MeeniMc** [comment]
same problem on windows 11.

**Comment by Dyvinia** [comment]
I'm on windows 10, and ive got the same issue

**Comment by thesuzerain** [comment]
Does this still occur on the latest update? (0.3.1)

**Comment by thesuzerain** [comment]
Marking as resolved as it seems to be fixed, please reopen if not!
