### ISSUE TITLE
Microsoft Account Authentication in system browser

### ISSUE THREAD

**Issue by Sxtanna** [modrinth/theseus#159]
### Is your suggested enhancement related to a problem? Please describe.

It would be nice if logging in with your MS account would happen through the system's browser if available.

### Describe the solution you'd like

Similar to the behavior of the mod [AuthMe](https://modrinth.com/mod/auth-me).

When attempting to login with a Microsoft account, your browser opens and you enter your Microsoft credentials.

**Comment by CodexAdrian** [comment]
Fixed in #347
