### ISSUE TITLE
Mod Updater - mods without a provider

### ISSUE THREAD

**Issue by Baconbacon123** [modrinth/theseus#160]
### Is your suggested enhancement related to a problem? Please describe.

I frequently use the check for updates button, and every time I need to tell it to ignore mods that aren't from modrinth or curseforge. 

### Describe the solution you'd like

Let me mark the mod to always be ignored.

### Describe alternatives you've considered

You could also remember that I pressed ignore on that mod, and not ask again.

**Comment by Geometrically** [comment]
you can already do this by using the checkbox and then update selected
