### ISSUE TITLE
Does not launch on Linux

### ISSUE THREAD

**Issue by nijahplays** [modrinth/theseus#163]
### Describe the bug

Does not launch

### Steps to reproduce

launch the appimage

### Additional context

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedPlatform', theseus_gui/src-tauri/src/main.rs:91:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by intergrav** [comment]
(geo is currently working on a fix for this)
![image](https://github.com/modrinth/theseus/assets/42325132/cc63ff03-df48-45af-853d-a07d11c6d023)

**Comment by nijahplays** [comment]
https://github.com/modrinth/theseus/assets/70035007/eb903b58-83d5-41ce-ac9f-a1a6e30afa01

**Comment by Caliel666** [comment]
i believe it broke in this [commit](https://github.com/modrinth/theseus/pull/132/commits/df477f1efc95805b47ea1d31d99165fd16723d97)

**Comment by Caliel666** [comment]
#179 fixed it !
![image](https://github.com/modrinth/theseus/assets/38433434/c6826234-96b9-4e3d-9244-d73321828270)

**Comment by Geometrically** [comment]
fixed by #179
