### ISSUE TITLE
Ability to trasnfer instances from other launchers (MultiMC, Prism, Official Laucher, etc.)

### ISSUE THREAD

**Issue by Logboy2000** [modrinth/theseus#164]
### Is your suggested enhancement related to a problem? Please describe.

I currently use the prism launcher and transferring over all of my minecraft instances would be tedious.

### Describe the solution you'd like

It would be nice if when you first install the launcher it prompts you if you would like to transfer your instances from a seperate launcher.

### Describe alternatives you've considered

Manually moving over ther save data which, once again is very tedious.

**Comment by Geometrically** [comment]
fixed in master
