### ISSUE TITLE
App bar blends too much

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#165]
### Is your suggested enhancement related to a problem? Please describe.

It's hard to distinguish between the app bar and the content on the page sometimes

### Describe the solution you'd like

Maybe a larger shadow on the bar? Or a slightly dark shade of gray, not sure

### Describe alternatives you've considered

Ignoring it

### Additional context

![image](https://github.com/modrinth/theseus/assets/25808801/d767faec-9194-48e2-86d6-23d0adffb67f)

**Comment by Prospector** [comment]
a shadow on it sounds good to me
