### ISSUE TITLE
Very minor visual dropdown menu bug

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#166]
### Describe the bug

When selecting an option from this dropdown, the options turn into rectangles for a split second (and when initially clicking on dropdown)

### Steps to reproduce

1. Go to an instance's page
2. Click on the dropdown
3. Select an option
4. See the rectangles for a split second

### Expected behavior

No rectangles, a maintained shape

### Additional context

https://github.com/modrinth/theseus/assets/25808801/5bba59cd-8edd-49fb-ae08-5b3189442b1a

**Comment by triphora** [comment]
This doesn't really seem like a bug to me. The animation is incomplete, and so is the styling of the elements. Also, the work that would be needed to fix this massively outweighs the benefit of doing so.
