### ISSUE TITLE
Browse Tab Infinite Load

### ISSUE THREAD

**Issue by Soufant** [modrinth/theseus#167]
### Describe the bug

When in the browse tab all categories load infinitely after switching to any category other than modpacks. Switching back to modpacks also loads infinitely.

### Steps to reproduce

1. Open the browse tab on the left side of the app.
2. Select any category other than the default 'Modpacks'.

### Expected behavior

Other categories are expected to load the requested content.

### Additional context

I am running Windows 10 Pro 22H2
![image](https://github.com/modrinth/theseus/assets/118411584/723ec083-7842-4ccb-b66d-ccbb3ffa6868)

**Comment by Geometrically** [comment]
already reported
