### ISSUE TITLE
Slight dividing line between sidebar and header bar

### ISSUE THREAD

**Issue by Pythagoras-314** [modrinth/theseus#171]
### Describe the bug

On the Modrinth App alpha, between the sidebear and the header bar there is a faint yet noticeable dividing line between the two sections, despite the fact that these are supposed to join into one entity.

MacOS Monterey
Alpha 2 (as of writing this bug report)

![screenshot](https://cdn.discordapp.com/attachments/1120926460065108031/1120930300617314397/Screen_Shot_2023-06-21_at_12.16.23_AM.png)

### Steps to reproduce

1. Launch the app
2. Look at the top-left side of the screen

### Expected behavior

The sidebar and header bar are joined together, without a dividing line.

**Comment by Geometrically** [comment]
this is intended, as the card is supposed to have a a shadow to separate it visually

**Comment by Minenash** [comment]
Then it shouldn't be the same color. This looks like a visual bug. If you want to visually separate it, a more visible separation could be used, like a vertical bar using a lighter color
