### ISSUE TITLE
Highlight on `Browse` is lost when changing from "modpacks" to anything else

### ISSUE THREAD

**Issue by LilWheezy** [modrinth/theseus#173]
### Describe the bug

Highlight on Browse is lost when changing from "modpacks" to anything else
![image](https://github.com/modrinth/theseus/assets/69182982/e4f97633-f8b1-4e43-b5fb-1102d616dedb)
![image](https://github.com/modrinth/theseus/assets/69182982/eda9033a-80a6-4481-9902-dea611a07b8b)

**Comment by triphora** [comment]
First two bugs are duplicates of #203 and #216.

Please create **one issue per bug**.

**Comment by thesuzerain** [comment]
Should be fixed with 0.3.0
