### ISSUE TITLE
Last played instances in the sidebar

### ISSUE THREAD

**Issue by KallelGaNewk** [modrinth/theseus#174]
### Is your suggested enhancement related to a problem? Please describe.

Last played instances in the sidebar, for quick access
![image](https://github.com/modrinth/theseus/assets/61438367/0d66a036-4402-4b03-a429-bc2f51b75ee5)

**Comment by Minenash** [comment]
I thought about suggesting something simular (not the exact same), but the problem is that more stuff will be added to the sidebar. For example: Modpack builder (I assume it would be it's own tab?) and stuff like that

**Comment by CodexAdrian** [comment]
We considered this when originally designing the app but ultimately felt it was cluttered.
