### ISSUE TITLE
Can't switch mod versions

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#176]
### Describe the bug

When switching the version of a mod, it will infinitely say it's `Installing...` and never actually switch versions

### Steps to reproduce

1. Install a mod
2. Switch its version
3. New version is never installed, old one persists

### Expected behavior

It should successfully switch versions

### Additional context

![image](https://github.com/modrinth/theseus/assets/25808801/a33fe792-b1ac-46e0-8f94-c33ee72d47a0)

**Comment by Geometrically** [comment]
fixed now
