### ISSUE TITLE
Different mod version page says `Installed` instead of `Switch`

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#177]
### Describe the bug

When opening a mod version that is different than the one currently installed, it will say the version is installed, when it should say something like `Switch`

### Steps to reproduce

1. Install a mod
2. Go to it's mod page in instance's browse
3. Select a different version than what's currently installed
4. It'll say `Installed` when it's not

### Expected behavior

To say `Switch` instead of `Installed`

### Additional context

![image](https://github.com/modrinth/theseus/assets/25808801/4f3a9bb8-6df0-414b-b594-c76c182b606e)

**Comment by thesuzerain** [comment]
Should be fixed with 0.3.0
