### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by SlinkousArt** [modrinth/theseus#18]
```
~/Code/theseus/ cargo run
   Compiling theseus_gui v0.1.0 (/home/slinkous/Code/theseus/theseus_gui/src-tauri)
error: proc macro panicked
  --> theseus_gui/src-tauri/src/main.rs:12:13
   |
12 |   let ctx = tauri::generate_context!();
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: The `distDir` configuration is set to `"../build"` but this path doesn't exist

error: could not compile `theseus_gui` due to previous error
~/Code/theseus/ 
```

OS: Arch Linux
CPU: Ryzen 7 5700G
Terminal: Kitty
Shell: Bash

Not sure if this is a known issue but figured I'd post it here anyway.

**Comment by Code-Ac** [comment]
I think I had this issue too while trying to get it running. Going into theseus_gui and running `pnpm i; pnpm run dev` fixed it for me. (Creates build files)

**Comment by SlinkousArt** [comment]
Thanks, that worked for me. 

This is truly the epitomy of app design.
![image](https://user-images.githubusercontent.com/83504509/156855097-492d6783-2c37-4adf-bd16-d4bd8857c8dd.png)
