### ISSUE TITLE
Some loader icons in search turn black

### ISSUE THREAD

**Issue by TheClashFruit** [modrinth/theseus#190]
### Describe the bug

2 projects this happens to:

![Modrinth_App_5ZNHL5xowP](https://github.com/modrinth/theseus/assets/55049569/905c160f-37fb-4c5c-a1e1-150af1b8920b)
![Modrinth_App_SmsEaoMmTg](https://github.com/modrinth/theseus/assets/55049569/c27f209c-5b83-42a7-a768-71e3b02e069b)

### Steps to reproduce

1. Click Add content in a Instance
2. Start searching for mods
3. Some mods' loader icons will turn black

### Expected behavior

Icons shouldn't turn black.

### Additional context

Happened on Windows 10 Build 19044.

**Comment by thesuzerain** [comment]
Thanks for the report, and your patience for this!
Does this happen consistently- is it still happening?

If so, can you please send me a copy of your tags.json file, which is either in:
-windows => C:\Users{username}\AppData\Roaming\com.modrinth.theseus\caches\metadata

mac => /Users/{username}/Library/Application Support/com.modrinth.theseus/caches/metadata
linux => /.config/com.modrinth.theseus/caches/metadata
(I am particularly interested in the bukkit/bungeecord/spigot snippets of it)

**Comment by TheClashFruit** [comment]
It no longer happens in 0.5.0
