### ISSUE TITLE
The launcher opens twice when it should be opening once

### ISSUE THREAD

**Issue by Imzxhir** [modrinth/theseus#191]
### Describe the bug

Basically the title, the launcher opens twice when I only click opened the launcher once. I have a feeling this is an incompatibility issue with my macOS version which is 10.13.6.

Screenshots:
![image](https://github.com/modrinth/theseus/assets/98621617/b81f7392-f466-4d63-9854-eeb4149462ee)

### Steps to reproduce

1. Open the Launcher
2. See if another launcher window opens seperatly
3. You have found the bug!

### Expected behavior

The expected behaviour is for the launcher to open once rather than two times.

### Additional context

Model: iMac (27-inch, Mid 2010)
macOS: High Sierra
macOS Version: 10.13.6

**Comment by pascil** [comment]
Can confirm.

Model: Mac Mini (2020, M1)
macOS: Ventura
macOS Version: 13.4 (22F66)

**Comment by thesuzerain** [comment]
Should be fixed with current 0.2.2 version
