### ISSUE TITLE
Being able to downgrade a modpack

### ISSUE THREAD

**Issue by BNKLovesTrollin** [modrinth/theseus#194]
## Changing modpack versions
Basically being able to change the modpack's version if available.
## Changing modpack to a not-available version
If that minecraft version is not available for that modpack then users can manually change the modpack's version.
By manually I mean changing the minecraft's version and modrinth automatically changing the mod's version with it too; and if the mod wasn't available for that version it would alert the user that the mod for that version is unavailable and will be disabled.

### Describe alternatives you've considered

Prism Launcher, MultiMC and etc Kinda have that feature by being able to change the minecraft version and updating the mods but it won't update the mods automatically and downgrading the mods are not possible

### Additional context

In the launcher people only can change the modpack's mod loader/game version and not the modpack version
_No response_

**Comment by Madis0** [comment]
Related to #328 which seems to be fixed as of 0.4.0, but I agree - allowing users to (optionally) specify which version to upgrade/downgrade to would be great.
