### ISSUE TITLE
Profile Naming

### ISSUE THREAD

**Issue by Kompanjuu** [modrinth/theseus#195]
### Is your suggested enhancement related to a problem? Please describe.

Currently profile folder are named as per their ID. This is very confusing for users that manually want to replace or add mods or want to have control over profiles.
 (+) No duplicate profile IDs/Folders.
 (+) Third party programs will always access the same profile because the name won't change.
 (-)  Hard to navigate or identify a profile as an user.

Example of name: 8006344b-f1d4-40a9-bd6d-283da600d776

### Describe the solution you'd like

Create folder names based on profile name. Whenever a profile with a duplicate name is created just add a (1) at the end (simplified explanation).
 (+) Easy to access as an user.
   -> Easier to manually change mods or use third party programs to do so.
 +/- Kind of duplicate folders but at the same time not.
 (-) Renaming the profile will make the folder name outdated OR renaming the profile will make the folder rename itself which leads to third party incompatability.

### Describe alternatives you've considered

The alternative is just to do nothing. The current solution isn't bad, just worse for user experience.

### Additional context

Problems:
 * Naming won't correspond to profile ID. Which means that the app need to store profile ID somewhere else.
    * IDs are stored in a config file.
      (-) An profile import system is needed.
    * IDs are stored in a hidden file in each profile folder.
      (-) Duplicating a profile will duplicate the profile ID. Ending with 2 profiles with the same ID.
 * I'm not a legal expert but some of these points are DIRECTLY taken from Curseforges approach at profiles, naming etc.

**Comment by thesuzerain** [comment]
Should be fixed with 0.3.0
