### ISSUE TITLE
rework on "popular packs" and "popular mods" button

### ISSUE THREAD

**Issue by fakechips** [modrinth/theseus#196]
### Is your suggested enhancement related to a problem? Please describe.

![Schermafbeelding 2023-06-21 131100](https://github.com/modrinth/theseus/assets/133385586/66e5c1de-c817-4963-9dd4-9b1a57f50678)
![Schermafbeelding 2023-06-21 131115](https://github.com/modrinth/theseus/assets/133385586/49297ab8-5bab-49b5-abc0-644479bdf4b8)
when you open the launcher there are two clickable pieces of text, i am reffering to "popular packs" and "Popular mods", these are clickable but its not immediately clear that they are, there is also a arrow behind the buttons that does not have click detection even though it would be my personal first instinct to click on the arrow as if it were to be a drop down menu.

### Describe the solution you'd like

personally i think that there should be a little but of a darker box behind the buttons to make them pop out a little more and make them look clickable.

and of course also it would be preferred if the click detection was also spread across the little ">" arrow

### Describe alternatives you've considered

i thought of two other ways to solve this issue,
- there could be a launcher tutorial on the first launch of the launcher, though the major downside of this would be that it would be a lot of work
- the text could have a little shine like the enchanting glint or something along those lines

### Additional context

https://health.gov/healthliteracyonline/organize/section-4-5/
this suggestion stems from this little article that shows how to make buttons look clickable.

**Comment by CodexAdrian** [comment]
a tutorial is now part of the launcher
