### ISSUE TITLE
Sorting button not great and more sorting options

### ISSUE THREAD

**Issue by MeeniMc** [modrinth/theseus#201]
### Is your suggested enhancement related to a problem? Please describe.

In the instance mod view interface; the sorting button is separated from the headline categories. 

In many OSs and GUI systems, sorting is done by simply clicking the relevant category in the headline (see how its done in windows explorer, for example).

That would remove the need for a clunky, separate button to select sorting options.

### Describe the solution you'd like

The headline of categories are clickable, first click on category heading sorts ascending by this category, subsequent clicks toggle between ascending/descending sort.

In addition, I'd like to have more sorting options (and thus category headlines), notably;
1. Last updated (that is, locally, a date)
2. Last update available (that is, on the server, should sort by update date, yet also show update version)

Mockup:

| [ ] | Name^ | Author | Version | Update Available | Last Updated | Enabled |
|---|---|---|---|---|---|---|
| [ ] | Aaaa | someone | 1.0 | 1.1 | 06/12/23 | [x] |
| [ ] | Abb | someone | 2.0 | - | 06/11/23 | [x] |
| [ ] | C | somebody | 1.0 | 2.0 | 04/01/22 | [ ] |

| [ ] | Name | Author | Version | Update Available^ | Last Updated | Enabled |
|---|---|---|---|---|---|---|
| [ ] | Aaaa | someone | 1.0 | 1.1 | 06/12/23 | [x] |
| [ ] | C | somebody | 1.0 | 2.0 | 04/01/22 | [ ] |
| [ ] | Abb | someone | 2.0 | - | 06/11/23 | [x] |

**Comment by Minenash** [comment]
A profile might be screen real estate, on smaller screens (maybe even 1080p?) columns are already having problems with content length

**Comment by MeeniMc** [comment]
fair point, I'd be ok to let go of the author's column (that info can be found in the mod page, and is not immediately actionable when managing installed mods)

**Comment by CodexAdrian** [comment]
This was changed a little while ago

**Comment by MeeniMc** [comment]
While the changes that have been implemented are welcome, this is still not quite where it needs to be IMO. 

1. The last update date is still not available
2. Sorting by 'status' is not effective, as it does nothing, in particular it doesn't sort the mods with an available update
