### ISSUE TITLE
Microsoft login bug

### ISSUE THREAD

**Issue by Michax777** [modrinth/theseus#215]
### Describe the bug

![obraz](https://github.com/modrinth/theseus/assets/40125094/a0e35b3c-1217-4955-b288-70b7eac2a4cd)

### Steps to reproduce

1. Click offline accounts
2. Login
3. Get window login successful
4. nothing changes
5. get error

### Expected behavior

login to account

**Comment by thesuzerain** [comment]
Marking as the same bug as #293 (even though you were first). Thanks for the report

**Comment by thesuzerain** [comment]
Duplicate of #293

**Comment by thesuzerain** [comment]
Duplicate of #293
