### ISSUE TITLE
Duplicate/Copy instance

### ISSUE THREAD

**Issue by CodeF53** [modrinth/theseus#229]
### Is your suggested enhancement related to a problem? Please describe.

Take for example me starting a new 1.20 instance. In a normal launcher I would
1. duplicate/copy my current 1.19 instance
2. switch the instance version to 1.20
3. update my mods

Currently there is no way to Duplicate instances in Theseus 

### Describe the solution you'd like

Add a "duplicate instance" button.

**Comment by CodeF53** [comment]
Concept by @a-person1908

![](https://user-images.githubusercontent.com/137985347/250228701-9baa9fc7-c2c2-4bba-a8d7-34540ab6b55c.png)

**Comment by StormDragon-64** [comment]
Could also be an option when right clicking an instance when you're in the library tab, kind of like curseforge's option to duplicate a profile: 
![image](https://github.com/modrinth/theseus/assets/80718549/431045c0-a952-4aa0-9192-cabc4c4d0e08)
