### ISSUE TITLE
Going to next page/changing filters should scroll to the top

### ISSUE THREAD

**Issue by CodeF53** [modrinth/theseus#230]
### Describe the bug

Upon changing a filter or page, the modrinth website scrolls to the top, while Theseus stays at the same place

https://github.com/modrinth/theseus/assets/37855219/6915e1cc-fff2-437b-8f5b-d575c87ecbe0

### Steps to reproduce

1. go to any project browser
2. scroll to bottom of page
3. click next page or change filter

### Expected behavior

It should scroll back to the top

**Comment by thesuzerain** [comment]
Should be fixed with 0.3.0

**Comment by CodeF53** [comment]
https://github.com/modrinth/theseus/assets/37855219/a4da88d7-8125-4fac-b7c2-e31d2f982ee7

**Comment by thesuzerain** [comment]
good to know thanks, I'll give another look
