### ISSUE TITLE
PathBuf#set_extension messes up version names

### ISSUE THREAD

**Issue by Bendimester23** [modrinth/theseus#24]
Minecraft version names contain dots, but Rust's PathBuf interprets it as an extension which is being changed in `theseus/src/launcher/download.rs` on line 26 to json. This messes up version names in files as shown in this image:
![image](https://user-images.githubusercontent.com/58264102/159975509-50262d44-af5b-4e17-ad1a-1f2a1ffd66f4.png)
However when starting the game, the version jar file is added to the classpath as `1.18.2-0.13.3.jar`, causing an error on Fabric and a crash on vanilla.
![image](https://user-images.githubusercontent.com/58264102/159975882-c6a6dbb3-71ad-4706-850f-29b02cd87c6e.png)

One not too elegant but working solution would be to just use PathBuf#push to append the .json and the .jar extension to the filename.

**Comment by enderger** [comment]
This is actually fixed by #17
