### ISSUE TITLE
"Light Mode" Colour Theme

### ISSUE THREAD

**Issue by bdmax1040** [modrinth/theseus#240]
### Is your suggested enhancement related to a problem? Please describe.

It would be nice to have the option to view the Modrinth App in "Light Mode", as well as "Dark Mode". When on MacOS, I have my device scheduled to change appearance between light and dark mode at set times so having both a light and dark mode, as well as a "System Setting" option to follow the systems appearance would be amazing!

### Describe the solution you'd like

In the settings page, adding additional options alongside the dark option to be:

- System Setting
- Dark Mode
- Light Mode

This could default to dark mode as most users will be wanting this setting, but having the option for light mode helps in high-contrast environments.

**Comment by JustAUser869** [comment]
without light mode, its just sad

**Comment by Felix14-v2** [comment]
@Geometrically has the System theme been implemented? In the launcher settings I see only Dark/Light/OLED
![image](https://github.com/modrinth/theseus/assets/75726196/16c68202-42c6-40a9-962a-c0368861a1b5)

**Comment by Felix14-v2** [comment]
@Minenash , the system theme hasn't been implemented, should I create another issue or could you reopen this one?

**Comment by Minenash** [comment]
Found the issue, #1022
