### ISSUE TITLE
Launcher CLI: Settings Management

### ISSUE THREAD

**Issue by Geometrically** [modrinth/theseus#25]
The launcher CLI should have an easy way to manage settings. I think we should make this elegant. Whereas a lot of CLIs have cumbersome settings, we can make it easy with prompts and good autocomplete.

Could be a command like `theseus settings` or several subcommands, up to implementation/what works best.

**Comment by enderger** [comment]
The main reason was due to binary size, since it is surprisingly heavy for
what it does.
