### ISSUE TITLE
Modpack stuck on installing

### ISSUE THREAD

**Issue by natewombwell** [modrinth/theseus#258]
### Describe the bug

# Bug Report: Modpack Stuck on installing
## Description of the bug
Whenever I make a new modpack it will be stuck on installing... Left PC on for a hour and same thing.

![image](https://github.com/modrinth/theseus/assets/89249903/c47ed37a-ab50-4c69-9605-f9b005ad3704)

## **_How to reproduce_**
1. Click on the **New Instance** button
2. Make a modpack
3. It will be stuck on **installing**

## What I expected to happen
I expected the modpack to finish installing after 1-3 minutes.

**Comment by Geometrically** [comment]
should be fixed now/can't repro

**Comment by gr8-png** [comment]
I've got the same problem, did you find out about it?

**Comment by xela154** [comment]
i have this problem has anyone solved it?

**Comment by RedstoneMaster011** [comment]
What Fixed It For Me Is Restarting Your Pc And Then A Repair Button Showed Up For Me Instead Of The Play Button
