### ISSUE TITLE
Launcher CLI: Project Information Query

### ISSUE THREAD

**Issue by Geometrically** [modrinth/theseus#26]
This should take a slug/project ID and display information about a project (title, description, categories, downloads, followers, etc)

This could show the icon in an ASCII format? Not sure if there's a good library for it. I know some terminals just support images outright.

This should also have some subcommands:

- [ ] Version listing
- [ ] Changelog view

**Comment by ModProg** [comment]
We could use https://lib.rs/crates/viuer for displaying images
