### ISSUE TITLE
Make it more obvious what file is missing

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#262]
### Is your suggested enhancement related to a problem? Please describe.

When an important file, such as a Java one, is missing, it'll just give you an error like this: `I/O error: The system cannot find the path specified.`

### Describe alternatives you've considered

I think it'd make much more sense to actually tell you what file is missing so that it can be more easily debugged and fixed.

**Comment by thesuzerain** [comment]
Should be fixed with 0.3.0
