### ISSUE TITLE
Delete Minecraft Account

### ISSUE THREAD

**Issue by MyDrift-user** [modrinth/theseus#265]
### Is your suggested enhancement related to a problem? Please describe.

It is easy to misclick and accidentally remove one of your Minecraft accounts.

### Describe the solution you'd like

Put a double-click requirement on the remove account button.
You could dye them in different colors and maybe put a warning that the removal needs a second click as a confirmation.

![image](https://github.com/modrinth/theseus/assets/121827219/e0cb1e6b-8a2c-4915-9892-117cdce64499)

![Screenshot 2023-06-25 122931](https://github.com/modrinth/theseus/assets/121827219/c6beae94-c49e-491a-b69d-bddc735a2b56)

### Describe alternatives you've considered

If really needed you could make a whole GUI dedicated to confirming the removal of the account.

**Comment by thesuzerain** [comment]
Closing as unplanned- see #298
