### ISSUE TITLE
Launcher CLI: Search

### ISSUE THREAD

**Issue by Geometrically** [modrinth/theseus#27]
The search can either be real time (through some cool CLI stuff) or just through arguments. The search command should have support for category filtering, loader filtering, game version filtering, index selection, and offsets/pagination.

**Comment by ModProg** [comment]
Looking into implementing this.

Should we maybe use/create a rust library wrapping the modrinth rest api, there are some but not sure if there should maybe be one belonging to the modrinth organisation: https://lib.rs/search?q=modrinth+api
