### ISSUE TITLE
App crashes right after install windows 11

### ISSUE THREAD

**Issue by thedarkcr0w** [modrinth/theseus#273]
### Describe the bug

App crashes and doesn't launch on latest version of Windows 11.
The system specs: 
Ryzen 5 5600x
32gb ram
3060ti 
Windows 11 latest, all the updates installed.
Java 20 

### Steps to reproduce

1. Install the app
2. Trying to launch it
3. App opens and then closes quickly

**Comment by SigmoidZebra844** [comment]
Do you have EdgeWebView2 installed? I had the same issue and i was able to fix it by installing it.

**Comment by Milstilteinn** [comment]
HI Team,
i cant get it to open and i have EdgeWebView2 installed

**Comment by thedarkcr0w** [comment]
It didn't fix the issue and I think people wouldn't prefer needing that to run the launcher

**Comment by Geometrically** [comment]
please go to support channels- cannot repro
