### ISSUE TITLE
Onboarding has several issues.

### ISSUE THREAD

**Issue by MagmaBro123** [modrinth/theseus#279]
### Describe the bug

Launcher seems to bring up the onboarding screen commonly, even after initial setup.

![image](https://github.com/modrinth/theseus/assets/51277766/769996f9-8858-449f-a8bc-a7c4bd0a48fd)

The Java install page also doesn't include 2 sections for Java 8 and 17 to be put into.
Java settings page (what Onboarding should have):

![image](https://github.com/modrinth/theseus/assets/51277766/9f568634-0b1e-4798-b543-aa060966c4b9)

Auto-Java-install also seems to cause an error.

![image](https://github.com/modrinth/theseus/assets/51277766/2e7a226e-be66-447a-bc98-7064fc009567)

### Steps to reproduce

Use the launcher for the first time.

### Expected behavior

Onboarding to not have these issues.

### Additional context

N/A.

**Comment by CodexAdrian** [comment]
Onboarding has been changed in #347
