### ISSUE TITLE
Random error when installing a modpack

### ISSUE THREAD

**Issue by cootshk** [modrinth/theseus#282]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/83678457/98a37c06-3cee-4aed-ad50-0bf68903d41e)
Random error occured about something not being managed

Windows 11 Home, just installed

### Steps to reproduce

Make a blank pack
Install a modpack
Delete the blank pack
This error occurs

### Expected behavior

Not get a confusing error

### Additional context

I can't find the file its mentioning in file explorer

**Comment by thesuzerain** [comment]
Thanks for your report and patience.

I'm having trouble reproducing this. Does this happen consistently every time you try to do these steps? What screen are you on when this happens (ie: the home screen, the screen for the blank pack, the modpack, the library, etc)

**Comment by Geometrically** [comment]
fixed now
