### ISSUE TITLE
Minecraft java never launches after pressing launch.

### ISSUE THREAD

**Issue by Minecraftplayer20** [modrinth/theseus#286]
### Describe the bug

I am using Minecraft 1.20.1 with forge version 47.0.1 and I have mods on it when I click play nothing happens
here is my latest log: https://gist.github.com/Minecraftplayer20/7e64e9d722a0a074b98ecb43a8455e78
and here is my debug log: https://gist.github.com/Minecraftplayer20/7630006015136877abb0d66b7850d14f

### Steps to reproduce

1. Go to your instance you want to play
2. click on play
3. see error

### Expected behavior

for minecraft to launch

**Comment by thesuzerain** [comment]
Thanks for the report! I have a couple questions:
- What OS are you on? Windows, Mac, Linux? What version of that?
- Does this error still happen with a vanilla instance (no mods)? What about with only forge and no other mods? 
- What are your java settings? (If you look at your settings page you should see some filepaths- where have you installed Java, and what version?)

**Comment by Minecraftplayer20** [comment]
> Thanks for the report! I have a couple questions:
> 
> * What OS are you on? Windows, Mac, Linux? What version of that?
> * Does this error still happen with a vanilla instance (no mods)? What about with only forge and no other mods?
> * What are your java settings? (If you look at your settings page you should see some filepaths- where have you installed Java, and what version?)

Im on windows 11
vanilla minecraft 1.20.1 runs fine and forge 1.20.1 without mods also runs fine
this is my java 8 filepath: C:\Program Files\Java\jre1.8.0_341\bin\javaw.exe
this is my java 17 filepath: C:\Program Files\Common Files\Oracle\Java\javapath_target_11141968\javaw.exe

**Comment by Geometrically** [comment]
can't repro- please go to support channels

**Comment by Minecraftplayer20** [comment]
> can't repro- please go to support channels

Where is support channels is it on the discord?

**Comment by triphora** [comment]
Yes, #app-support on https://discord.gg/modrinth
