### ISSUE TITLE
Can't sign in with Minecraft account on launcher

### ISSUE THREAD

**Issue by Mapty231** [modrinth/theseus#293]
### Describe the bug

When i try and sign in with my Minecraft account i can get though all the Microsoft sign in then once i've finished it this image shows up ![image](https://github.com/modrinth/theseus/assets/131195812/5e451090-e7d0-4961-8de5-de050bba893d) 
and my account doesn't appear in the accounts list.

And i get an error about parsing an id at line five, i would've copied the text exactly but when i tried to i got a new error
![image](https://github.com/modrinth/theseus/assets/131195812/e8c90d51-0daa-4440-94be-7378014bff13)

### Steps to reproduce

Sign in

### Expected behavior

My account should register properly

### Additional context

I already have one account registered that does work

**Comment by thesuzerain** [comment]
Thanks for the report! 

Just want to make sure I understand, with one account ,everything works fine, but when you log in with your second account (so that there are two accounts on the launcher), this happens?  So if you are logged in with account A, and then you attempt to log in with account B, you get this?

Does it happen if you sign out of all of them, then do B first, _then_ A?

**Comment by Mapty231** [comment]
The error still occurs when I sign out of all accounts and try to sign in with the one that is having problems.

I also managed to capture the error this time.
![image](https://github.com/modrinth/theseus/assets/131195812/95c5a302-d4a0-4769-8afa-391e751eb40d)

**Comment by thesuzerain** [comment]
Thanks! I'll look into it. 

If it only happens to that account, that's interesting. My last question would be is there anything unusual about the account or account name? Any weird characters in the username, a free trial account, a microsoft account unconnected to minecraft, etc?

**Comment by Mapty231** [comment]
The name of the account is "testing32" and it was migrated from a Mojang account to a Microsoft one, but aside from that I can't think of anything unique about it. And I'm using it fine with the vanilla launcher. If you want I can try relogging with it in using the vanilla launcher?

**Comment by Geometrically** [comment]
should be fixed now
