### ISSUE TITLE
Ability to view mod lists of modpacks

### ISSUE THREAD

**Issue by Logboy2000** [modrinth/theseus#301]
### Is your suggested enhancement related to a problem? Please describe.

Having to download a modpack to see what mods it has or making modpack creators manually put a list is annoying.

### Describe the solution you'd like

Add a tab to each modpacks page that shows the mods and mod count

### Describe alternatives you've considered

downloading modpacks to check.

### Additional context

a really bad mockup i made:
![example](https://github.com/modrinth/theseus/assets/72185335/3ce58c49-e742-4657-bc1b-122d99644ebb)

**Comment by CodexAdrian** [comment]
You can view the mod list of any given version of a modpack by clicking it in the versions list and seeing the dependencies
