### ISSUE TITLE
No way to go back from opened site

### ISSUE THREAD

**Issue by JosefLitos** [modrinth/theseus#307]
### Describe the bug

When a an external link is opened (I would expect it to be in my normal browser) it opens the link within the app, which itself acts as a simplified browser, but now loading a different page. Currently, after opening a page, there is no way to get back to the app nor close it (requires force kill).

### Steps to reproduce

go to any webpage (using `site` option when on a mod page or any other way)

### Expected behavior

open site in external browser by default and/or provide a back button (`Alt+Left` / `Esc` ...)

### Additional context

BTW "Open in Modrinth" option should be "Open in external browser" or something like that to reflect its actual functionality.

**Comment by CodexAdrian** [comment]
Fixed in #350
