### ISSUE TITLE
Cut off entries when changing the game version

### ISSUE THREAD

**Issue by tr7zw** [modrinth/theseus#312]
### Describe the bug

![grafik](https://github.com/modrinth/theseus/assets/5133936/8c10f7c1-45ee-4557-8ad4-910431591668)
The first two entries in the "Change instance version" Game Version selection are cut off, and can only be selected by using the arrow keys and spacebar.

**Comment by CodexAdrian** [comment]
I cannot seem to replicate this 
<img width="1212" alt="image" src="https://github.com/modrinth/theseus/assets/83074853/9e916a7c-d041-46d4-b073-00cd38f27b79">

**Comment by tr7zw** [comment]
Not sure if auto-update is working, but it's still happening for me.
