### ISSUE TITLE
Updating mods breaks the UI

### ISSUE THREAD

**Issue by tr7zw** [modrinth/theseus#313]
### Describe the bug

When pressing the update button, the spinning Modrinth icon will not go away/the shown version doesn't update(the file does get updated in the background). In this state, the Home/Library buttons stop functioning at all.

https://github.com/modrinth/theseus/assets/5133936/744fbf50-0e23-4935-8a58-1da4fde9b662

**Comment by Edeec0** [comment]
the same thing happends to me

**Comment by KPaXz** [comment]
ive experienced this aswell, closing the launcher and reopening fixes it. the mod also got updated during the lockup

**Comment by KewlSage** [comment]
still an issue on the new update, and the removal of the update all button makes it so i have to go to each mod that needs to update and install the new version from said mods own version page, additionally if the bug is triggered i have to kill from task manager.
