### ISSUE TITLE
The 'x' button that shows after searching something doesn't clear the search bar when clicked.

### ISSUE THREAD

**Issue by StormDragon-64** [modrinth/theseus#317]
### Describe the bug

The x button that I highlighted in the screenshot doesn't clear your search, it just plays a little animation when clicked and nothing actually happens.

![image](https://github.com/modrinth/theseus/assets/80718549/d8cf8cbf-0ac5-4f78-a2bc-be8c7d583e3c)

### Steps to reproduce

1: Create a new instance (I made a quilt 1.20.1 instance)
2: Go to add content
3: Search for a mod
4: Click x button after installing a mod
5: Nothing happens, and you have to manually erase what you wrote in the search bar :(

### Expected behavior

Clicking the x button after typing in the search bar would clear the search bar.

### Additional context

This only affects the add content search bar. The search bar that lets you search your already installed mods has an x button that does clear the search bar.

**Comment by WingedWhite** [comment]
but it doesn't work when searching for modpacks to install either.

**Comment by CodexAdrian** [comment]
Fixed in #350
