### ISSUE TITLE
You can scroll in the app while the "Getting Started" screen is focused.

### ISSUE THREAD

**Issue by ubionexd** [modrinth/theseus#320]
### Describe the bug

[This video describes it all.](https://github.com/modrinth/theseus/assets/70473378/d6dc9393-96bc-4425-9f1a-8c3e816723b1)  
You can scroll what's behind the "Getting Started" screen.

### Steps to reproduce

1. Open the Modrinth App for the first time.
2. Scroll!

### Expected behavior

While the "Getting Started" screen is focused, you shouldn't be able to scroll what is behind.

### Additional context

This version of the Modrinth App was compiled from source at Git commit [6650cc9](https://github.com/modrinth/theseus/commit/6650cc9ce431b61b5c9a9bf7361b47e4e0e6facf).

**Comment by ubionexd** [comment]
Further exploring this bug it looks like this affects all pop-ups like the above mentioned "Getting Started" screen.

**Comment by Geometrically** [comment]
not a bug - this is intended
