### ISSUE TITLE
Incorrect sha-1 for 1.12.2 forge

### ISSUE THREAD

**Issue by Scrapmine** [modrinth/theseus#323]
### Describe the bug

When trying to download 1.12.2 forge I get this error:
An error occurred
Incorrect Sha1 hash for download: 
111e7bea9c968cdb3d06ef4632bf7ff0824d0f36 != 
d01c97e2944166ed23e47e4a62ff471ab8fa031f

### Steps to reproduce

1. Open modrinth app.
2. Create 1.12.2 forge instance.
3. When download finishes you get the error.

### Expected behavior

It dowloads 1.12.2 successfully.

**Comment by S1lencio** [comment]
Issue still exists and I dont see how this is intentional behaviour. Why was this closed as not planned?

**Comment by Geometrically** [comment]
it's a duplicate
