### ISSUE TITLE
Links not functioning on Getting Started pop-up

### ISSUE THREAD

**Issue by NovaCrypt** [modrinth/theseus#327]
### Describe the bug

When opening the app for the first time on linux using the appimage, the links in the getting started pop-up don't open anything. They blink to acknowledge the click but that's all.

### Steps to reproduce

1. Open app for the first time
2. click a link in getting started popup
3. witness bug.

### Expected behavior

I'd expect the github link to open the github issues page in the users default browser and the discord link to open discord with the invite link.

### Additional context

Bug experienced on the Linux Appimage using Manjaro KDE.

**Comment by CodexAdrian** [comment]
the getting started popup has been changed in #347 so i guess a fix isnt planned? idk, its no longer an issue so ill call it fixed
