### ISSUE TITLE
Next page scroll up?

### ISSUE THREAD

**Issue by WingedWhite** [modrinth/theseus#329]
### Describe the bug

When you go to the next page on a list of modpacks or just mods, it stayds at the bottom of the list.

### Steps to reproduce

1. Go to list.
2. Click page you want to go.
3. it stays at the height it was left before.

### Expected behavior

When switching pages it goes to the top of the page?
Not entirely a "bug" per se, but something I think most would expect to happen.

**Comment by netamari** [comment]
i think you should have added it as an enhansment

**Comment by thesuzerain** [comment]
Thanks for your report, this will be fixed in the next update!
