### ISSUE TITLE
Incorrect Sha1 hash for download

### ISSUE THREAD

**Issue by ElectricplaysGaming** [modrinth/theseus#330]
### Describe the bug

Incorrect Sha1 hash for download: 111e7bea9c968cdb3d06ef4632bf7ff0824d0f36 != d01c97e2944166ed23e47e4a62f

Whenever I try to make a 1.12.2 custom modpack

### Steps to reproduce

1. Tap '+ New Instance'
2. choose forge 1.12.2
3. click create

### Expected behavior

It should create a new instance using 1.12.2

### Additional context

Nope

**Comment by Geometrically** [comment]
fixed!

**Comment by KPaXz** [comment]
Awesome, thanks!

**Comment by BeckPhillips** [comment]
I'm having this issue - Minecraft 1.19.2 Forge brings up this error now.

**Comment by Enigmatron** [comment]
this is occurring with 1.19.2
