### ISSUE TITLE
Unable to change modpack/instance icon

### ISSUE THREAD

**Issue by FishIsGroovy** [modrinth/theseus#342]
### Describe the bug

When changing the icon of a modpack you have downloaded, it will not change and any changes to the name or file of the instance will not be registered either. After this, the app will pretty much break and will not load anything other than the browse tab.

![image](https://github.com/modrinth/theseus/assets/139757396/5dd0bcf9-53b0-4e89-9b6d-24d89ea33de1)

![image](https://github.com/modrinth/theseus/assets/139757396/5b5944da-e841-461a-a52d-f4e8321a8485)

![image](https://github.com/modrinth/theseus/assets/139757396/46833325-af02-445d-82d8-959a26bf5009)

### Steps to reproduce

1. Go to modpack/instance
2. Go to options
3. Select "Select Icon" and choose file

### Expected behavior

The profile/icon changed to the picture and everything running as normal.

**Comment by CodexAdrian** [comment]
Fixed in #298
