### ISSUE TITLE
I cant make a profile in Forge 1.12.2

### ISSUE THREAD

**Issue by NightsXC** [modrinth/theseus#343]
### Describe the bug

I have tried to make a profile in Forge 1.12.2 but it keeps saying error when im trying to create it.

### Steps to reproduce

Create a instance.
Select forge
Select 1.12.2
Press create.
=Error in bottom right corner.

### Expected behavior

I expected that i could be allowed to make a profile in that version on forge.

### Additional context

![image](https://github.com/modrinth/theseus/assets/139769799/1a464d9d-bdcd-42a3-8093-c4da135bb768)
![image](https://github.com/modrinth/theseus/assets/139769799/3dbf4cb3-decd-4f8d-a8d0-aeb5bdbd1f74)

**Comment by Geometrically** [comment]
duplicate
