### ISSUE TITLE
When adding modpack icon, the app partially stops working.

### ISSUE THREAD

**Issue by NotBadli** [modrinth/theseus#344]
### Describe the bug

When I'm adding the icon to a modpack, the app partially stops working. For example, when I switch to the "Home" or "Browse "page, it doesn't load. Also, the icon doesn't actually change. 

An image I tried to upload:
![skin-face](https://github.com/modrinth/theseus/assets/79380248/8cb4f343-ad03-4142-a84e-2b8965bfa833)

How the aftermath looks:
![image](https://github.com/modrinth/theseus/assets/79380248/69a9fc62-5af4-4229-9efb-42485265a039)

### Steps to reproduce

1. Go to any modpack.
2. Go to options.
3. Click on "Select icon".
4. Upload an image.

### Expected behavior

For an icon to actually get applied

**Comment by CodexAdrian** [comment]
Fixed in #298
