### ISSUE TITLE
How do I install this launcher?

### ISSUE THREAD

**Issue by TechPro424** [modrinth/theseus#36]

**Comment by DioEgizio** [comment]
You don't, it's still in heavy development

**Comment by Gaming32** [comment]
If you really want it badly, follow the instructions in https://github.com/modrinth/theseus/tree/master/theseus_gui#readme. However, this is highly technical and support likely won't be provided for it.

**Comment by Eskaan** [comment]
Most of the GUI wasn't functional last time I checked, currently only the Design is worked out and Implemented in Omorphia. The CLI already has some integration for the library: It can download and start a Game without automatic authentication.

**Comment by wafflecoffee** [comment]
See above. :)

**Comment by kreezxil** [comment]
ATLAUNCHER from https://atlauncher.com can both import and export Modrinth
packs. Use that for now until this launcher is installable. :)

**Comment by DioEgizio** [comment]
https://docs.modrinth.com/docs/modpacks/playing_modpacks/
