### ISSUE TITLE
Hello so this isnt working it keeps loading

### ISSUE THREAD

**Issue by MAmmMA-MIA** [modrinth/theseus#367]
### Describe the bug

i've found a bug, idk if its only to me but everytime i choose another category in browse (ex: mods) other than modpacks it keeps loading forever.

### Additional context

can somebody tell me if it happens to them too?

**Comment by MAmmMA-MIA** [comment]
![Screenshot 2023-07-27 165313](https://github.com/modrinth/theseus/assets/140724699/3e34f829-2aac-4615-b918-73852ac6e6c3)
here is a screenshot

**Comment by TomLord2000** [comment]
Same problem here, it keeps loading for every tab but the modpacks tab, the way i used it is by making a instance and then when you click on it you can add mods straight to it. 

https://github.com/modrinth/theseus/assets/57014240/c6f603f4-6bd0-4c05-b07c-5fe3e2213a1a

You can also add mods manually by opening the folder that the modpacks is in.
C:\Users\**YourUsername**\AppData\Roaming\com.modrinth.theseus\profiles

**Comment by Geometrically** [comment]
duplicate
