### ISSUE TITLE
Folder button opens wrong directory

### ISSUE THREAD

**Issue by SpiralshapeOfficial** [modrinth/theseus#369]
### Describe the bug

When pressing the folder buttons in a modpack, it only opens base "This PC" directory instead of opening the modpack's folder
![image](https://github.com/modrinth/theseus/assets/85375190/c56d6882-2aaf-4475-9c16-c7b4c109beaf)

### Steps to reproduce

1: Go to a modpack
2: Click The Folder Button

### Expected behavior

When pressing the folder button it is supposed to open the modpack's file location

### Additional context

This only started happening after I updated the app to the newest version

**Comment by Norbiros** [comment]
I get the same error on Linux.
```
gio: file:///tmp/.mount_theseuvbrM7u/usr/9449b9cd-42bb-4aee-9e5d-456c5cc072be: Error when getting information for file “/tmp/.mount_theseuvbrM7u/usr/9449b9cd-42bb-4aee-9e5d-456c5cc072be”: No such file or directory
```
But my files are located in:
```
/home/username/.config/com.modrinth.theseus/profiles/9449b9cd-42bb-4aee-9e5d-456c5cc072be
```

**Comment by srnyx** [comment]
Related to https://github.com/modrinth/theseus/issues/175
