### ISSUE TITLE
File navigator for exporting

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#371]
### Is your suggested enhancement related to a problem? Please describe.

This is very impractical and annoying, very hard to find files I want to include
![Modrinth_App_jcNZvJdf4T](https://github.com/modrinth/theseus/assets/25808801/64a448c8-f6c0-41f2-9217-74c38b964b7d)

### Describe the solution you'd like

A navigator where you can click to open certain folders and close them again, and maybe a bigger pop-up to give the navigator more room to view long file names

### Describe alternatives you've considered

Dealing with it I guess

**Comment by HyperSoop** [comment]
The dialog should be not for what to include in overrides, but for what to include at all. Mods, configuration files and resource pack would be enabled by default, the rest would be for the user to enable if they need it included; then the app would automatically detect which files can to be included without an override and only use overrides for the files that can't be.

**Comment by srnyx** [comment]
Maybe it could be a nicer selection for mods, so it'd look sorta like the mod list in an instance? That way you can just more easily see/select what mods you want to include.
