### ISSUE TITLE
Error: Missing correct java installation

### ISSUE THREAD

**Issue by wallwraf** [modrinth/theseus#380]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/85986630/c6f20786-c337-4554-81d5-573a4946fbbd)

What does this mean and how do I fix it?

### Steps to reproduce

1. Create new instance
2. Do whatever version on whatever loader
3. Click 'Create'

### Expected behavior

To make an instance using Modrinth.

**Comment by thesuzerain** [comment]
It probably means you have a java version unset in the settings- for example, if you have java 8 unset, you wont be able to run a profile that requires java 8 specifically.
Check the global settings!
The autodetector isn't working right now (#373, which will be fixed soon) which is probably why it wasn't automatically set, but you should be able to manually set it to the right folder of a java 8 or java 17 you have downloaded (and press test to ensure it is correct). Can you try that for now?

**Comment by Norbiros** [comment]
I am not sure if this is problem with auto detector. I have java installled in two paths (17.0.6):
```
/opt/openjdk-bin-17.0.6_p10/bin/java
/usr/bin/java
```
All of them work correctly. I can run minecraft using them etc. If I select `/usr/bin/java` this throws error:
```
An error occurred
Error launching Minecraft: Java path invalid or non-functional: /usr/bin/java
```
When I use other path, it works correctly.
