### ISSUE TITLE
Logs button does nothing and close button does not work

### ISSUE THREAD

**Issue by TheShadowModsUK** [modrinth/theseus#393]
### Describe the bug

So once the pack as created it it does not load logs it does a green loading bar and then nothing.
also on windows you click the X and it wont close at all.

### Steps to reproduce

Create ModPack 
Add mods
run game
close game
click logs

click X anytime.

### Expected behavior

Show logs.

close software.

### Additional context

**OS**: Windows 10 22H2 
**Modrinth**: Modrinth App 0.3.0 (Alpha)

**Comment by TheShadowModsUK** [comment]
Update to this, it seems it only stops losing when the green bar has loaded for Logs and got stuck.

**Comment by thesuzerain** [comment]
If you go into the /modrinth_logs subfolder of your instance, 

C:\Users\(you)\AppData\Roaming\com.modrinth.theseus\profiles\(instance)\modrinth_logs

Do you have logs there? Is there anything? 
Does it happen still if you restart the app?

**Comment by TheShadowModsUK** [comment]
It seems to only happen if its not running I will retest with a new instance tomorrow for you and to restart the app when this happens I have to end the tool via taskman

**Comment by Geometrically** [comment]
duplicate
