### ISSUE TITLE
No option to import/transfer instances from other launchers

### ISSUE THREAD

**Issue by Logboy2000** [modrinth/theseus#395]
### Describe the bug

My previous issue (#164) is "closed" but i see no option to transfer my instances. I also tried exporting it as a .zip from prism launcher and importing that as i file but no luck.

### Steps to reproduce

1. Open Modrinth app 0.3.0
2. Realize there is no option and create a GitHub issue about it

### Expected behavior

See an option to import instances or be prompted to transfer when opening for the first time.

### Additional context

Screenshots of no option being there

![image](https://github.com/modrinth/theseus/assets/72185335/58362f15-c997-45f7-88f2-598ef3d3beba)
![Screenshot 2023-07-28 222224](https://github.com/modrinth/theseus/assets/72185335/eabb0786-b9af-4f10-a1ee-ad797ed1a027)

**Comment by Logboy2000** [comment]
someone please tell me if im just dumb/missing something

**Comment by thesuzerain** [comment]
It’s closed because it’s been merged on GitHub, but wont be in a release until the update after 0.3.0- an initial beta importer will hopefully be available with the next update .
