### ISSUE TITLE
Broken Update Button

### ISSUE THREAD

**Issue by Theov0re** [modrinth/theseus#398]
### Describe the bug

Clicking the update mod button doesn't work. It just keeps doing the animation endlessly. Also, I always had to end the process with Task Manager because it never finished, even after over an hour.
![image](https://github.com/modrinth/theseus/assets/130942503/eb2c3225-2e17-4cc3-b721-cd71311ee8f6)

### Steps to reproduce

I don't know, create a profile with a mod that needs to be updated? Then try to update it.

### Expected behavior

Updates the mod normally.

### Additional context

Also, where did the update all button go? At the very least, there should be a way to do it all at once. If there's enough mods that needs updating, it's a giant pain to go through each one individually.

**Comment by thesuzerain** [comment]
Fixed with #381
