### ISSUE TITLE
[Bug] Opening instance Folder results in Documents being opend

### ISSUE THREAD

**Issue by Der-Floh** [modrinth/theseus#405]
### Describe the bug

When clicking the "Folder" button on an instance / profile the instance Folder isn't opened but instead the explorer just starts at the Documents Folder.

### Steps to reproduce

1. Create a new Profile
2. Click on the Profile
3. Click on the "Folder" (Open instance Folder) Button

### Expected behavior

Open the instance Folder. Which would by at %appdata%/com.modrinth.theseus/profiles/profilename

**Comment by thesuzerain** [comment]
Duplicate of #382
