### ISSUE TITLE
Update All Mods

### ISSUE THREAD

**Issue by MisterChaneb** [modrinth/theseus#409]
### Is your suggested enhancement related to a problem? Please describe.

There's currently an issue with knowing if the mods are outdated or not you would have to scroll and pinch ur eyes to see if mods need an update or not.

### Describe the solution you'd like

Maybe an Update All button would be a nice improvement to a simple issue

**Comment by thesuzerain** [comment]
There should be a mass 'update' option if you select more than one mod. so for example, if you click the checkmark at the top that selects 'all' of them, there should be an 'update' button that appears at the top that will update all selected ones :)
