### ISSUE TITLE
App doesn't launch modpacks

### ISSUE THREAD

**Issue by ElequacityYT** [modrinth/theseus#410]
### Describe the bug

when i press launch it gives me this error message:
Serialization error (JSON): missing field `token` at line 1 column 43

### Steps to reproduce

make a modpack
press launch

### Expected behavior

launching the game

**Comment by thesuzerain** [comment]
- Does this happen with every modpack? What if you download one of the recommended ones? What if you do a vanilla one? If not, what are the details of the modpack that it happens in?
- What system are you on? Windows, Mac, etc
