### ISSUE TITLE
Launcher does not know about minecraft versions released after it was opened

### ISSUE THREAD

**Issue by CodeF53** [modrinth/theseus#412]
### Describe the bug

Snapshots released after the launcher was downloaded (I think, its hard to confirm this), do not show up inside the "Create Instance" box

Left: launcher opened before the release of `23w31a`
Right: launcher open after the release of `23w31a`, inside of a sandbox, to not interfere with the left one.
![image](https://github.com/modrinth/theseus/assets/37855219/ccd347c5-b42e-4232-9b39-e9a9cbfa209e)

### Steps to reproduce

I have no idea how you could reliably reproduce this in a timely manner.

1. Leave launcher open until new Minecraft Version/Snapshot gets released
2. Attempt to create a new instance
3. Observe the lack of visibility of the Version/Snapshot in the dropdown

### Expected behavior

Upon opening "Create instance" the latest data from Mojang should be loaded as to allow discovery of new Versions of minecraft.

### Additional Context
Closing and reopening the launcher fixes the issue

**Comment by Geometrically** [comment]
known, you have to reopen the launcher to reload this

**Comment by CodeF53** [comment]
That's not a solution to the problem imo.

**Comment by CodeF53** [comment]
Closing and reopening the launcher is not a solution to the problem. It's a hacky workaround. Please actually fix it.
