### ISSUE TITLE
Logging on through Onboarding gives an error.

### ISSUE THREAD

**Issue by MagmaBro123** [modrinth/theseus#418]
### Describe the bug

Title.

![image](https://github.com/modrinth/theseus/assets/51277766/4fff7fd9-bb80-4305-aec5-3cb701663113)

![image](https://github.com/modrinth/theseus/assets/51277766/a39d3f09-0b96-46bd-9a09-b2094e5f4ffe)

### Steps to reproduce

Login via the Onboarding page.

### Expected behavior

Logging in to function.

### Additional context

N/A.

**Comment by HixxyDubz** [comment]
yup same here, and its been doing this ever since it has been public.

**Comment by MagmaBro123** [comment]
> yup same here, and its been doing this ever since it has been public.

My issue gives more detail then the one you opened, might wanna close that.

**Comment by Geometrically** [comment]
should be fixed now!
