### ISSUE TITLE
Intro sequence blur

### ISSUE THREAD

**Issue by OfficiallyDragon** [modrinth/theseus#421]
### Describe the bug

The intro sequence for the newest build of the Modrinth App (as of writing) is slightly blurry | I am using windows 10 1080P screen (idk if this is needed but I thought it would help 🤷‍♂️)

### Steps to reproduce

1. Open the modrinth app
2. Watch as it is blurry

**Comment by Geometrically** [comment]
wontfix, we may redo the animation at some point, it was made fairly quickly + in house
