### ISSUE TITLE
importing does not work (mod folder remains empty)

### ISSUE THREAD

**Issue by MisterChaneb** [modrinth/theseus#430]
### Describe the bug

I exported a profile I created, with which I wanted to play with friends. Before getting them involved, I tested importing the profile myself, but the imported profile was empty. The Json file shows all the mods*

### Steps to reproduce

Export a profile.
Import the profile.

### Expected behavior

After importing, I expected the mods and the shader to be there.

### Additional context

Using the latest version! & the mrpack is not working on prism aswell
https://anonfiles.com/Qdh6k463ze/modrinth_index_json

**Comment by thesuzerain** [comment]
Thanks for the report! Was the mrpack exported/created in the current version? Or was the .mrpack already exported, and you are now trying to import it in the current version?

**Comment by MisterChaneb** [comment]
> Thanks for the report! Was the mrpack exported/created in the current version? Or was the .mrpack already exported, and you are now trying to import it in the current version?

The one i have linked is the current version but i have tried with an older version aswell! and yes i've tried importing in an older version which didn't work* and now i have also tried for the newer version which also happened not to work ofc being the version that just came out minutes ago

**Comment by thesuzerain** [comment]
How exactly are you importing it? Are you going to the create instance, from file, and then selecting it from the 'from file' -> file selection popup?

I was able to import your modrinth.index.json and it seemed to populate with mods OK

**Comment by MisterChaneb** [comment]
> How exactly are you importing it? Are you going to the create instance, from file, and then selecting it from the 'from file' -> file selection popup?
> 
> I was able to import your modrinth.index.json and it seemed to populate with mods OK

Yes i'm indeed doing exactly that! I've first created the modpack in modrinth exported then simply tried importing from file using the mrpack file that i got from exporting.

**Comment by MisterChaneb** [comment]
> How exactly are you importing it? Are you going to the create instance, from file, and then selecting it from the 'from file' -> file selection popup?
> 
> I was able to import your modrinth.index.json and it seemed to populate with mods OK

While typing i've tried to do it again and now it worked i assume the issue just required a pc restart ofc.
