### ISSUE TITLE
Fetch error when trying to share logs

### ISSUE THREAD

**Issue by mvilk** [modrinth/theseus#432]
### Describe the bug

title
![](https://github.com/modrinth/theseus/assets/75657829/f5cc7ec0-046d-485b-92be-7693730060de)

### Steps to reproduce

1. Select instance and go to logs page.
2. Select log file.
3. Click "Share" button.
4. Error.

### Additional context

app version 0.3.1

**Comment by thesuzerain** [comment]
Does this continue to happen if you do it now? Or was this a once-off.

**Comment by Geometrically** [comment]
can't repro- please go to support
