### ISSUE TITLE
Attempting to import other launcher profiles throws error. "The system cannot find the path specified."

### ISSUE THREAD

**Issue by DolphinOfficial** [modrinth/theseus#436]
### Describe the bug

When attempting to import other Launcher profiles, trying to select the folder throws an OS error.
![error](https://github.com/modrinth/theseus/assets/92276540/4ff3593e-d809-4164-a994-0a90eab1ea1f)

### Steps to reproduce

1. Add a new profile
2. Click "Import From Launcher" 
3. Select any type
4. Select a folder
5. The error should occur

### Expected behavior

Expected behaviour: Profiles from Curseforge should appear
Actual behaviour: Throws error without showing profiles

**Comment by thesuzerain** [comment]
It is likely to be the incorrect folder. We want the folder outside the 'instances' folder 
(So in a curseforge case, it tends to be curseforge/minecraft/Instances', we want 'minecraft' to be the chosen one)

either way, this should be replaced with a more clear error message, so thank you for the report!
