### ISSUE TITLE
Launcher Fails To Launch

### ISSUE THREAD

**Issue by GRocket-GamingGalaxy** [modrinth/theseus#438]
### Describe the bug

I'm on linux and just updated modrinth to the new version and when I launch a window pops up but goes from gray to white to gray again but doesn't pull up anything.

### Steps to reproduce

1. downlaod latest appimage
2. launch

### Expected behavior

Open as normal

**Comment by TheoCGaming** [comment]
just out of curiosity, does the latest *git* version fix this issue?
