### ISSUE TITLE
Importing from Prism Launcher doesn't include instance icon

### ISSUE THREAD

**Issue by mvilk** [modrinth/theseus#439]
### Describe the bug

Title
![](https://github.com/modrinth/theseus/assets/75657829/235bda20-0c48-4aac-80a7-ce0e6e40910d)
![](https://github.com/modrinth/theseus/assets/75657829/1073247d-17a6-4b93-92e0-0416c6a73d53)

### Expected behavior

Importing should include instance icon.

### Additional context

Windows 11
app version 0.3.1

**Comment by GeraldTM** [comment]
this happens with importing from .mrpack files as well

**Comment by thesuzerain** [comment]
Is this primarily happening for the icons compiled into the prism launcher? Like the modrinth logo, the bee, etc.

**Comment by GeraldTM** [comment]
hmmm .mrpack imports must be a seperate issue then, as all of them do not have icons

**Comment by thesuzerain** [comment]
Closing- I think that decompiling their default icons is not currently planned.  The .mrpack ones should be fixed in #455
