### ISSUE TITLE
dragging a file to import it is broken

### ISSUE THREAD

**Issue by GeraldTM** [modrinth/theseus#440]
### Describe the bug

draging a .mrpack on to the launcher window apears to work, but only creates an empty instance

### Steps to reproduce

1. download any modpack from modrinth
2. drag that file onto the modrinth app window
3. watch your "downloads" tab go crazy
4. open instance to find it empty (no mods, resource packs, or shader packs)

### Expected behavior

the modpack to download correctly

### Additional context

I am on version 0.3.1 of the modrinth app

**Comment by thesuzerain** [comment]
Can I ask what screen you are on as you try this? For example, are you dragging them onto the home screen, vs the library screen, vs dragging them onto the screen of a specific instance, etc

**Comment by GeraldTM** [comment]
I believe I tried it on both the home and library tabs, same thing on both

**Comment by GeraldTM** [comment]
I tried it with both my own personal mrpack, as well as that of Fabulously Optimized
