### ISSUE TITLE
Forge 1.12.2 instant crash

### ISSUE THREAD

**Issue by DolphinOfficial** [modrinth/theseus#447]
### Describe the bug

When creating or launching any Forge 1.12.2 profile, the game instantly crashes the moment it starts. This makes all 1.12.2 profiles unusable.

Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

https://github.com/modrinth/theseus/assets/92276540/1adb97f9-425d-4fca-b247-8be03a1e156a

### Steps to reproduce

1. Create or download a Forge 1.12.2 profile
2. Launch the profile
3. The game crashes instantly

### Expected behavior

Expected behaviour: Game will launch normally
Actual behaviour: Instant crash

### Additional context

This may affect other profiles, as I have seen the 1.7.10 Forge profile also instantly crashing with a similar error.
Test all profiles in Forge to make sure that they aren't crashing.

**Comment by Geometrically** [comment]
What OS are you on?

**Comment by DolphinOfficial** [comment]
> What OS are you on?

Windows 10

**Comment by thesuzerain** [comment]
What are your java settings? If you go to your Settings page, there should be several java options
I'm interested in the paths you have (absent any personal information) and whether or not the test shows a 'success' when you click it, and whether not any of the autodetected other java settings work for you if you try them.

Thanks!!!

![image](https://github.com/modrinth/theseus/assets/10837000/d74920a2-a512-4bfb-943b-94f0f3be97d1)

**Comment by DolphinOfficial** [comment]
> What are your java settings? If you go to your Settings page, there should be several java options I'm interested in the paths you have (absent any personal information) and whether or not the test shows a 'success' when you click it, and whether not any of the autodetected other java settings work for you if you try them.
> 
> Thanks!!!
> 
> ![image](https://user-images.githubusercontent.com/10837000/258499373-d74920a2-a512-4bfb-943b-94f0f3be97d1.png)

Yeah, the Java settings was what messed it up. I changed it to what was shown here, and I can launch 1.12.2 profiles now! Thanks!
