### ISSUE TITLE
Warning about crash when importing instance

### ISSUE THREAD

**Issue by mvilk** [modrinth/theseus#448]
### Describe the bug

Title
![](https://github.com/modrinth/theseus/assets/75657829/cdd75560-1caf-4096-b675-38487aa66e20)

### Steps to reproduce

Can't reproduce every time, but has happened twice for me now.
1. Open modrinth app.
2. Import instance (I imported from PrismLauncher).
3. get error like shown in image above.

### Expected behavior

Instance shouldn't be able to crash since I have never even launched it with Modrinth app.

### Additional context

Windows 11
Modrinth app 0.3.1

**Comment by thesuzerain** [comment]
After the warning, does the instance continue to install/work after installation?

The 'running' comes from the forge processors which run the instance to some degree. Is that the default installation of Hexxit on prismlauncher?

**Comment by thesuzerain** [comment]
Gotcha thanks. This warning is confusing as its weird to have the process 'run' before its done installing- I'll silence it pre-installed warnings
