### ISSUE TITLE
Can't open Modpack Path

### ISSUE THREAD

**Issue by Rajala1404** [modrinth/theseus#457]
### Describe the bug

I can't open the Modpack folder even if i do it in Minecraft self

### Steps to reproduce

Click on Folder

### Expected behavior

I have expected that my Explorer open with the Folder

### Additional context

I am on Linux and using the AppImage

And can anyone say where the Modpacks are located

**Comment by thesuzerain** [comment]
Does any folder open at all? What happens when you press the button?

**Comment by Caliel666** [comment]
i can confirm this is a issue, not sure how you are making it open the folder but it's falling to get the mimetype to find the application and just opens the folder path in a web browser

```shell
egrep: warning: egrep is obsolescent; using grep -E
xdg-mime: no method available for querying MIME type of '/home/username/.config/com.modrinth.theseus/profiles/Fabulously Optimized'
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
```

if you aren't already i suggest using just `xdg-open`  instead

**Comment by Rajala1404** [comment]
> Does any folder open at all? What happens when you press the button?
It just do nothing

**Comment by Rajala1404** [comment]
> i can confirm this is a issue, not sure how you are making it open the folder but it's falling to get the mimetype to find the application and just opens the folder path in a web browser
> 
> ```shell
> egrep: warning: egrep is obsolescent; using grep -E
> xdg-mime: no method available for querying MIME type of '/home/username/.config/com.modrinth.theseus/profiles/Fabulously Optimized'
> xdg-mime: mimetype argument missing
> Try 'xdg-mime --help' for more information.
> ```
> 
> if you aren't already i suggest using just `xdg-open` instead

Ok Thanks i hope this will be fixed
