### ISSUE TITLE
Error Fetching Project

### ISSUE THREAD

**Issue by hdent1232** [modrinth/theseus#465]
### Describe the bug

I am not sure why this error started showing up but sometime between yesterday and today the modrinth app just stopped being able to load project pages. I have changed nothing in my settings or to the app, I have tried logging out and logging in, I have tried stopping the process in task manager, and I've tried restarting my computer but I keep getting this error saying it cant fetch the project page. this is across the entire app, from the home page to the add content button etc. I know my internet connection is fine as I can use all other wifi related apps just fine. Not sure how to fix it or why it happened
![Screenshot 2023-08-04 233757](https://github.com/modrinth/theseus/assets/131039005/551a0cd0-3ce0-4c97-8071-997df7078da6)

**Comment by hdent1232** [comment]
literally right after I decide "I cant seem to figure out why this is happening or how to fix it, maybe I should report it as a bug" it seems to have just started working again, really not sure why this was happening but I'll close the issue for now

**Comment by Dekalliver** [comment]
happens to me, too. Project: "Fabulously Optimized"
