### ISSUE TITLE
Logging in with github doesn't work

### ISSUE THREAD

**Issue by Pro42good** [modrinth/theseus#472]
### Describe the bug

I tried logging in with github and the login api page said i could close the window and i went back to the app and i wasn't signed in, also Yes i had a account with modrinth already that used github.

### Steps to reproduce

1. go to settings
2. click sign in under Account
3. log in using github
4. go back and you aren't logged in

### Expected behavior

You aren't logged in.

**Comment by Parilia** [comment]
Happens to me in appimage, button does nothing 
using Nobara 38

**Comment by thesuzerain** [comment]
Can you confirm if this happens in the latest version?

**Comment by Lamdarer** [comment]
Can confirm, I still cant login using Github, I am on Linux using the AppImage version 0.5.4

**Comment by Tschipcraft** [comment]
Works fine on Windows

**Comment by Lamdarer** [comment]
I added a Password to my github Microsoft login(on the MS management page->Security->Add password (or something like that)) and tried to login and using that and it worked, after restarting Modrinth and my PC I was logged in to my Minecraft/MS-Github account in Modrinth(0.6.0 AppImage via Lutris)!
So setting a saperate Login password seems to work as workaround for now

**Comment by MtgSaber** [comment]
Getting this issue too. Using AppImage on Kubuntu, the GitHub button on the sign in menu does nothing. Sometimes, after a while, there is an error popup regarding connection closing and handshakes, but I couldn't get one to come up to snip a screenshot for this comment.
