### ISSUE TITLE
Ability to Choose Pack Install Location

### ISSUE THREAD

**Issue by InfinitlyUndefined** [modrinth/theseus#473]
### Is your suggested enhancement related to a problem? Please describe.

No, it is not related to a problem.

### Describe the solution you'd like

It would be a really nice feature to have a global option to choose the install location of your modpacks. Some people, like me, have separate drives from the C:\ drive that we use for game storage. It would be a nice feature to have the ability to set the installation path of modpacks

### Describe alternatives you've considered

I haven't considered alternatives, it is a suggestion.

**Comment by Geometrically** [comment]
fixed in a future update
