### ISSUE TITLE
Update mod button

### ISSUE THREAD

**Issue by Rhyn0w0** [modrinth/theseus#476]
### Is your suggested enhancement related to a problem? Please describe.

there is no convenient way to update a mad to its latest version

### Describe the solution you'd like

![image](https://github.com/modrinth/theseus/assets/79499550/87174ca3-fb66-438c-b113-4a9e9fe6c8dd)
rather than just saying installed, if there is an available update for a mod on the chosen version of Minecraft, have the "installed" button say "update"

### Describe alternatives you've considered

another alternative could be auto updating mods, i feel like that could be potentially better especially if a profile could store mods as a list of links and grab the latest update of every mod (that isn't already installed) for the chosen version of Minecraft. this would also make it much easier to switch versions of Minecraft because you wouldn't have to reinstall anything, just swap the instance version and wait or the mods to all autoupdate.

**Comment by Geometrically** [comment]
this is already a thing, its the one that looks like a refresh button on your profile mods page
