### ISSUE TITLE
Option to also show Fabric mods by default on Quilt modpacks

### ISSUE THREAD

**Issue by Treetrain1** [modrinth/theseus#488]
### Describe the solution you'd like

It would be nice to have an option to have Quilt modpacks search for mods or mod updates for the Fabric loader as well, reason being some Fabric mods don't select Quilt for each uploaded version, causing their results to be excluded.

I am aware this is possible by overriding loaders *every time* when browsing for mods, but there is not a way to override loaders when the launcher is checking for mod updates. It can also be tedious to override loaders every single time I want to browse mods.
![image](https://github.com/modrinth/theseus/assets/39657565/94a834ce-9ed9-45b8-932e-0d2b877d1bc9)

**Comment by CodexAdrian** [comment]
Not all fabric mods are supported on Quilt, so making this assumption is not safe for users. Its a fairly common issue, I myself have fabric mods that do not work on quilt at the moment. The override was added here for this issue, allowing pack makers to see other mods on other loads knowing that there might be some risk doing so.
