### ISSUE TITLE
Allow the ability to disable the included Launcher RPC

### ISSUE THREAD

**Issue by CDAGaming** [modrinth/theseus#491]
### Is your suggested enhancement related to a problem? Please describe.

The Launcher RPC will interfere with RPC mods present in Minecraft, such as CraftPresence (By me) and Simple RPC (By HypherionMC).

### Describe the solution you'd like

This ticket is requesting the addition of a toggle to control whether or not the Launcher RPC is enabled,
in order to allow users to choose if they want the Launchers RPC or to use a mod in addition to allowing RPC mods such as the two aforementioned products to work properly without interference.

**Comment by MaybeScripted** [comment]
**really** want this ngl

**Comment by Filipsi** [comment]
I have raised same issue on Discord, ability to disable Discord Rich Presence would come in handy.

**Comment by PetyXbron** [comment]
@thesuzerain checked the PR but I don't see any specific details about the ability to disable Discord RPC and did not see this feature in the client. By the way, is the Modrtinh app auto-updated, or how can I update it?

**Comment by CDAGaming** [comment]
@PetyXbron https://github.com/modrinth/theseus/pull/703/files#diff-63423b292ef11e4c2412029304f71043ad695a8521b0f5ba355d267b9f9d6298R192

There is a setting for it in the diff, I'll try to find if its in the frontend.

**Comment by PetyXbron** [comment]
@CDAGaming, great! But I don't see it. To update my launcher I can only wait for a new GitHub release, am I right?

**Comment by thesuzerain** [comment]
This feature will be available quite soon- the PR is merged meaning so it will be included when we release the next version.
