### ISSUE TITLE
YOSBR mod does not copy options.txt

### ISSUE THREAD

**Issue by Madis0** [modrinth/theseus#504]
### Describe the bug

The mod YOSBR does not work fully as intended with Modrinth app. I've filed the issue here and not [in the mod's repo](https://github.com/shedaniel/your-options-shall-be-respected) because it works as intended with other launchers, such as CurseForge, Prism, MultiMC, GDLauncher...

### Steps to reproduce

1. Install Modrinth app
2. Create a Fabric instance (e.g. 1.20.1)
3. Click -> Add content -> search "[YOSBR](https://modrinth.com/mod/yosbr)" on Mods -> Install
4. Go back to home -> right click the instance -> Open folder
5. Create folder "config", inside that "yosbr", inside that text file "options.txt"
6. Open the text file and write [an option](https://minecraft.fandom.com/wiki/Options.txt) that can easily be tested for, e.g. `guiScale:1`
7. Run the instance

### Expected behavior

Expected the GUI scale to be 1, as the options.txt file should be copied to root folder by the mod. That, however, does not work.

### Additional context

YOSBR can also copy mod config files (not described here), this seems to work.

FYI, this issue is also present on Pojav Launcher, but there at least the options.txt is intentionally overridden to support mobile phones better. In Modrinth app, this is obviously not the goal, so it is a valid bug.

**Comment by exelash** [comment]
Can reproduce.

**Comment by thesuzerain** [comment]
Will be fixed except when laucher settings that override options.txt are toggled on (ie: force fullscreen)
