### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by zefir-git** [modrinth/theseus#517]
### Describe the bug

I saw exactly the same issue being reported and closed as "duplicate" or "should be fixed" however I failed to find the duplicate of which or the pull request that fixes this as it was not mentioned.

The issue prevents me from logging in and the following error is thrown:
```json
{"error":"In Bearer token flow: Response didn't contain valid bearer token. body: {\n \"path\" : \"/launcher/login\"\n}"}
```

### Steps to reproduce

1. Open app
2. Click "Get started"
3. Click "Sign in"
4. Complete the Microsoft authentication flow
5. Observe the error in the app as well as in your browser (HTTP 500)

### Additional context

Using Linux AppImage on Fedora 38 x64

**Comment by ewpratten** [comment]
(on exactly the same platform as you)

I discovered that skipping through the intro login flow, getting to the main menu, *then* logging in with the button in the top left works just fine.

**Comment by srnyx** [comment]
This is happening to me, trying to add my second account (I'm not adding via onboarding)

**Comment by Pomegranate123** [comment]
I've got the exact same issue (except I'm running on windows). It seems that after I restart my computer, the session is lost and I need to login again, but it doesn't allow me. After ~5 minutes of trying to log in it suddenly starts working again without explanation.

**Comment by mineTomek** [comment]
I was going through the menus and relogged to the modrinth account and it worked.

**Comment by NgLoader** [comment]
I have the same issue.
I'm trying to rejoin a server, but my session got denied.
After that, I attempted to restart the game to refresh my token.
Once I clicked "Play" again, the Launcher prompted me to re-login into my Microsoft account.

I encountered the following error when I tried to log in to my Microsoft account:
"Minecraft authentication Hydra error: In Bearer token flow: Response didn't contain a valid bearer token."

**Comment by TheAlan404** [comment]
for the curious, modrinth's servers kind of handle the microsoft authentication

the error originates from this file:

https://github.com/modrinth/labrinth/blob/master/src/auth/minecraft/stages/bearer_token.rs

**Comment by StormDragon-64** [comment]
I have the same issue (I'm on windows 11). I didn't have this issue until today, but when I tried to play an instance, it said there was an issue with my Minecraft account. So, I then removed/signed out of my account and tried to re-add it to modrinth, and then this error showed up. After reopening the app, I still get the same error when trying to sign back in with the same Microsoft account I used yesterday.

**Comment by Tom60chat** [comment]
Ok, so the solution is to spam the account sign in literally.

**Comment by shimizu-izumi** [comment]
@Tom60chat 's solution doesn't work for me.

**Comment by qtchaos** [comment]
> @Tom60chat 's solution doesn't work for me.

This is currently the only workaround and it has worked for a lot of other users, I suggest simply trying again every 5-10 minutes until you get in. This is due to Microsoft rate limiting Modrinth.

**Comment by zefir-git** [comment]
This might have been fixed in #594 however there is no mention of this issue there or of that PR here for anyone possibly having a similar issue in the future to find.

**Comment by srnyx** [comment]
> This might have been fixed in #594 however there is no mention of this issue there or of that PR here for anyone possibly having a similar issue in the future to find.

They announced in the Discord that it was fixed

**Comment by zefir-git** [comment]
> > This might have been fixed in #594 however there is no mention of this issue there or of that PR here for anyone possibly having a similar issue in the future to find.
> 
> They announced in the Discord that it was fixed

Sorry, I'm not in the Discord and people who find this issue might not be either.

**Comment by triphora** [comment]
It is fixed

**Comment by srnyx** [comment]
> Sorry, I'm not in the Discord and people who find this issue might not be either.

All good! Here's the announcement they made:

> We've fixed the launcher authentication issues! sorry for taking so long. Let us know if you have any more issues with it!! 
![image](https://github.com/modrinth/theseus/assets/25808801/21246d20-6f5a-4b55-af0d-a799bec52cb4)
