### ISSUE TITLE
UI selecting non-text

### ISSUE THREAD

**Issue by zefir-git** [modrinth/theseus#518]
### Describe the bug

When dragging the app, or selecting text in the app, you are able to select non-text elements including images and boxes. This appears to be outside of the expected behaviour and usually on desktop apps you cannot select any text except text that you may specifically need to copy (e.g. ids, tokens) and of course in text input fields.

![image](https://github.com/modrinth/theseus/assets/66572326/fb8b15ac-5a8c-45d0-b937-170bbd886681)

**Comment by thesuzerain** [comment]
related to #467
