### ISSUE TITLE
Cannot import packs created from Launcher with Quilt Loader

### ISSUE THREAD

**Issue by ZesilinaNewborn** [modrinth/theseus#519]
### Describe the bug

I've created a pack that has all the mods I want on Quilt and have exported it using the launcher's export feature, but every time I try to import it on another pc, I get the error that the loader ver is invalid, tried this on multiple loader versions however, I sill get the same "invalid loader ver" error. 

PS: This is an old bug that still happened in launcher ver 0.2.0 and 0.3.0.

**Screenshot showing that the launcher has the loader version I used when exporting pack**
![quilt loader version](https://github.com/modrinth/theseus/assets/95070196/12d1ed87-0355-4f35-9fa1-8ab49e7f855f)

**Video showcasing issue below**
https://github.com/modrinth/theseus/assets/95070196/bce48e2b-472a-43fd-855f-2814dc670229

### Steps to reproduce

1. Create a pack with Quilt and choose the loader version you want
2. Add the mods you want from the "Add Content" button
3. Export the pack using the launcher
4. Try importing that same pack after exporting it
5. Encounter error

### Expected behavior

Importing should not fail as you can recreate the same pack in the launcher from scratch and have it works fully without an import

### Additional context

I've tried with both loader versions 0.17.9-beta 1 and 0.20.0-beta 11 so far with both having this issue

**Comment by craftish37** [comment]
*Not recreating an issue since this one exists*

As discussed on discord, the issue is that `"quilt-loader": "beta.xx"` while we need to input `"quilt-loader": "0.20.0-beta.xx"` to work
The change can be made manually via any archive editor (7-Zip etc...)
