### ISSUE TITLE
Update modpack button is visible even when there are no updates for modpack

### ISSUE THREAD

**Issue by mvilk** [modrinth/theseus#523]
### Describe the bug

When that button is visible it gives the feeling that there is update for modpack.
![](https://github.com/modrinth/theseus/assets/75657829/e16835b0-de9d-4de6-856e-ff1a387dfe8a)

### Steps to reproduce

1. Install modpack (I installed Modfest Singularity).
2. Go to settings of the modpack you just installed.
3. Look at top right corner and see the "Update modpack" button.
4. Try to click it, nothing happens since there are no updates available.

### Expected behavior

Update modpack button should be invisible/or disabled when there are no updates for modpack.
Alternatively, there could be "Check for updates" button when no updates are detected.

### Additional context

Windows 11
Modrinth app 0.4.0

**Comment by thesuzerain** [comment]
Should be fixed with 0.5.0
