### ISSUE TITLE
Linux- Using window resize handles triggers the scrollbar

### ISSUE THREAD

**Issue by mystchonky** [modrinth/theseus#525]
### Describe the bug

Whenever you try to resize the window using the right edge, it also triggers the scroll

https://github.com/modrinth/theseus/assets/51489635/e3486936-5a77-48fa-8019-56f603635b47

(Ignore the glitchy-ness. Its probably just wayland)

### Steps to reproduce

1. Go the search modpack screen
2. Try to resize the window using the right edge 

### Expected behavior

Resize operations should take priority and block scrolling

**Comment by wlad26** [comment]
Can confirm on Windows 11 and latest App version ( v0.6.3 )

**Comment by wlad26** [comment]
Seems to happen only if you're using non-system window frame option, using window resize handles with native frame doesn't trigger the scrollbar
