### ISSUE TITLE
Include back button when navigating projects

### ISSUE THREAD

**Issue by Owehttamy** [modrinth/theseus#528]
### Is your suggested enhancement related to a problem? Please describe.

I was looking at a mod pack, checking out the dependencies/mods in the project, as some of them were unfamiliar to me. After checking an individual mod out, I noticed there needs to be a way to return to the mod pack's page without navigating to the home page or manually searching for the mod pack again.

Dramatic reenactment:

https://github.com/modrinth/theseus/assets/47429979/4eb8b6c0-35b0-43c5-8505-291366d18848

You also need a back button when searching for projects, clicking on one, then wanting to return to the search results you just had.

### Describe the solution you'd like

Add a simple back button like you'd find in a web browser to navigate projects and their dependencies more easily.

### Describe alternatives you've considered

A little view history tab on the left toolbar, maybe? For example, the icons of the last three projects you viewed would show up there?

I'm sure there are multiple options to improve navigation to be explored, but a back arrow would be fine.

**Comment by Prospector** [comment]
Like the breadcrumbs that already exist at the top of every page?

**Comment by mxruben** [comment]
A temporary workaround is that if you have a 5-button mouse you can use the extra 2 buttons for forward and back navigation.
