### ISSUE TITLE
blank search while downloading

### ISSUE THREAD

**Issue by AlexanderwithaA** [modrinth/theseus#529]
### Describe the bug

When you try to search for a modpack while another is already downloading the search section vanishes.
![image](https://github.com/modrinth/theseus/assets/101488091/399f31d6-966d-40e1-97a5-85f7ce2cfc02)

### Steps to reproduce

1. start downloading a modpack
2. the search page will either just vanish after this starts or you'll have to reload it.

### Expected behavior

Still able to search for modpacks to download while one is currently downloading.

**Comment by thesuzerain** [comment]
I'm having trouble reproducing this.
- What type of OS are you on?
- Are you logged in (either minecraft account in top left, modrinth account in settings, or both?)
- Is the launcher entering offline mode when it does so? 
- Are you downloading a modpack from the browse directly? Did you create a modpack while doing it (ie: downloading a mod into the mods section)

**Comment by AlexanderwithaA** [comment]
- Windows 11
- logged in with minecraft only
Does this icon in the top right signify whether you're in offline mode? Since if that's the case it does go into offline mode while downloading. I'm downloading modpacks through the app if that's what you're asking on the last point and am not creating any modpacks.
![image](https://github.com/modrinth/theseus/assets/101488091/80c88fe4-519e-4e57-9c97-7e2231f111c6)

**Comment by AlexanderwithaA** [comment]
- Windows 11
- logged in with minecraft only
Does this icon in the top right signify whether you're in offline mode? Since if that's the case it does go into offline mode while downloading. I'm downloading modpacks through the app if that's what you're asking on the last point and am not creating any modpacks.
![image](https://github.com/modrinth/theseus/assets/101488091/80c88fe4-519e-4e57-9c97-7e2231f111c6)

**Comment by thesuzerain** [comment]
Does this still happen on the latest version?

**Comment by AlexanderwithaA** [comment]
No, not anymore.
