### ISSUE TITLE
Error fetching URL

### ISSUE THREAD

**Issue by ubionexd** [modrinth/theseus#539]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/70473378/260bd13d-7a89-43a5-9ba7-1e0e4f6978f3)
Error happens while the Modrinth App is downloading Minecraft.
![image](https://github.com/modrinth/theseus/assets/70473378/d60b1186-00c5-42a2-b065-ad1f57cfe576)

### Steps to reproduce

1. Install the Modrinth App for the first time
2. Try to install any modpack

### Expected behavior

The modpack installs without errors.

### Additional context

Windows 11 22H2

**Comment by Wawwior** [comment]
I get exactly the same issue with exactly the same context; Also fails at 98%

**Comment by thesuzerain** [comment]
Does this still happen on the latest update?

**Comment by ubionexd** [comment]
> Does this still happen on the latest update?

No, I don't think so. I didn't use the Modrinth App for a while and it solved itself.

**Comment by thesuzerain** [comment]
awesome. Im gonna close- we fixed a lot of things around this area so its likely it was fixed as a part of it. Please reopen if it occurs again
