### ISSUE TITLE
Loader version list is not sorted properly

### ISSUE THREAD

**Issue by Andre601** [modrinth/theseus#548]
### Describe the bug

When looking through the "Loader Version" list will you notice that the versions aren't sorted properly.

As an example, using Quilt for 1.20.1 will display these values in order:

- `0.17.9-beta.1`
- `0.17.2-beta.3`
- `0.17.2-beta.2`
- `0.17.2-beta.1`
- `0.20.0-beta.1`

This sort order not only makes no sense no matter what logic you apply (Nummerical won't work as `0.19.x` versions appear later on) but also seems to include versions not related to the actual MC version you use (0.17 afaik is not a MC 1.20.x compatible loader version).

### Steps to reproduce

1. Edit a profile
2. Go to the Options
3. Open the Loader Version dropdown

### Expected behavior

The list should be sorted properly, preferably newest version to oldest (Maybe use date to determine that?).
Additionally only list versions that would be compatible with the selected MC version, if the metadata provided by the loader allows to check that.

### Additional context

I've checked other launchers such as PrismLauncher and there are the loader versions sorted properly from newest to oldest.

**Comment by thesuzerain** [comment]
This should be fixed as of the most recent update
