### ISSUE TITLE
CurseForge Modpack support

### ISSUE THREAD

**Issue by Phisika1** [modrinth/theseus#552]
### Is your suggested enhancement related to a problem? Please describe.

I wanted to play All the Mods 7: To the Sky, and I realized, that All the Mods doesn't exist on Modrinth. So I downloaded the ZIP, wanted to import it into the Modrinth App, but it said, that no Manifest-File was found, but it was. I think it just doesn't recognize the modpack format of CurseForge. I even tried to rename the extension to .mrpack, but then it gave me a different error.

### Describe the solution you'd like

It would be really helpful if you introduce the support for CurseForge-Modpacks.

### Describe alternatives you've considered

If there will be legal problems, you could also consider to just ask the All the Mods-Developers, if you could add their Modpack to Modrinth.

**Comment by Prospector** [comment]
Nothing we can do about this. Instead, download the modpack with another launcher like Prism or the CurseForge app and import it into the Modrinth app
