### ISSUE TITLE
Realms page popup

### ISSUE THREAD

**Issue by pointwoods** [modrinth/theseus#563]
### Describe the bug

Realms page asking to purchase a realm. Cannot access realms.

### Steps to reproduce

1. go to realms when invited to one
2. purchase realms popup appears and doesn't let you access any realms you are already in.
![image](https://github.com/modrinth/theseus/assets/111038136/2136ed49-c7a9-4a83-8844-760652146f22)

### Expected behavior

I expected my realm to appear and allow me to join it.

**Comment by MIfoodie** [comment]
This is not a problem with Theseus, this may be a problem with Minecraft. To report a bug with Minecraft, please use this link. https://www.minecraft.net/en-us/bugs

(and did you try clicking the X at the top left corner of the popup?)

**Comment by pointwoods** [comment]
Yes, I did try clicking the x, it just brings you back to the title screen, and when you re-open the realms menu, it's still there.

I wasn't entirely sure if this was a problem with Theseus at the time of posting, but since I was having this issue only when launching with Theseus, I took a shot in the dark and posted here. I'll go ahead and make a post to the bugtracker.

**Comment by MIfoodie** [comment]
Hmm maybe it could also be a problem with one of your mods if you have them installed. Just an idea.

**Comment by thesuzerain** [comment]
This actually was correctly a bug with theseus (and a very strange one) but should be fixed as of 0.5.3 with #631 . If it still reoccurs please reopen the issue! :)
