### ISSUE TITLE
It is recommended to add language options

### ISSUE THREAD

**Issue by Buelie** [modrinth/theseus#570]
**I'm a user from China and I'd like modrinth to add language options instead of just English.Adding language options can also make the experience better for users in more regions**

**Comment by Buelie** [comment]
> Partial Chinese translation: <br>

Home       主页
  Popular packs           热门整合包
Browse     浏览
  Loaders                    加载器
  Minecraft Versions    Minecraft版本
  Environments            环境
  Open source             开源
  Include snapshots     显示所有版本
  mod                         模组
  modpack                  整合包
  Resource Packs         资源包
  Shaders                    光影
  Data Packs                数据包

Mod
  Adventure                 冒险
  Cursed                      改良
  Decoration                装饰
  Economy                   经济
  Equipment                装备
  Food                         食物
  Game Mechanics       游戏机制
  Library                      支持库
  Magic                        魔法
  Management             管理
  Minigame                  小游戏
  Mobs                         生物
  Optimization              优化
  Folia                          社会
  Storage                     存储
  Technology                 科技
  Transportation            运输
  Utility                         效用
  World Generation        世界生成

Modpack:
  Adventure                 冒险
  Challenging               挑战
  Combat                     战斗
  Kitchen Sink               水槽
  Lightweight                轻量
  Magic                        魔法
  Multiplayer                多人
  Optimization              优化
  Quests                       任务
  Technology                 科技

**Comment by Buelie** [comment]
[language_zh_cn.txt](https://github.com/modrinth/theseus/files/12326147/language_zh_cn.txt)

**Comment by triphora** [comment]
Localization is on our [roadmap](https://roadmap.modrinth.com) - please do not create issues for items that are on our roadmap.
