### ISSUE TITLE
Can't login into my Modrinth account

### ISSUE THREAD

**Issue by IBlazingX** [modrinth/theseus#576]
### Describe the bug

I'm trying to login into mi Modrinth account with Google, Github, Microsoft, Discord but the buttons dosen't redirect me to a login screen, it do nothing. Also I try to login with my email and password but I got an error.

![image](https://github.com/modrinth/theseus/assets/80444690/31af24d8-d556-4781-bc9e-1ff5bb27cdd1)

### Steps to reproduce

1. Go to `Settings`
2. Click `Sign in` on `General settings > Manage account`
3. Click any button below `Login to Modrinth` or click `Login` button below it

### Expected behavior

Want a web redirect to login or login after putting my account credentials

### Additional context

**OS:** Arch Linux x86_64
**Kernel:** 6.4.10-arch1-1
**CPU:** Intel Celeron N3160 (4) @ 2.240GHz
**GPU:** Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx
**Memory:** 1876MiB

**Comment by IBlazingX** [comment]
I try to login with my account credentials and its work today, but the buttons doesn't work (Microsoft, Google, etc..)

**Comment by MeIsGaming** [comment]
Restarting the launcher seems to work

**Comment by thesuzerain** [comment]
These should be fixed with authentication changes in newest update, though you may have to log out/in
