### ISSUE TITLE
🌟Multiple amazing ideas to improve the Modrinth app experience

### ISSUE THREAD

**Issue by User4716** [modrinth/theseus#579]
# 💡So here are all of my suggestions:
Remember that you guys don't have to do any of these, I'm just giving you ideas ❤️
ㅤ
ㅤ
## 📒Better Logs

**- The logs would look much cleaner and be more intuitive and speed up a troubleshooting process if they would have COLORS**

Gray messages for DEBUG logs

White for INFO
![image](https://github.com/modrinth/theseus/assets/97033682/6e0920e8-31a2-4442-813b-cf11ef10c28f)

Yellow for WARN
![image](https://github.com/modrinth/theseus/assets/97033682/7ae2fd94-1fb9-4074-b5ba-ef1344fb95eb)

Red for ERROR
![image](https://github.com/modrinth/theseus/assets/97033682/16e9be7b-e0fa-4273-93b3-f462c2c462b7)

White text and red background, or dark red for FATAL ERROR (This one should only be seen if your game crashes)
![image](https://github.com/modrinth/theseus/assets/97033682/ae3dd047-7e31-4675-8ea6-008718688c28)

It would be cool if we could have a filter search box, and the ability to enable/disable the visibility of certain log messages 
(For example, hide all debug messages.)
![image](https://github.com/modrinth/theseus/assets/97033682/a498ac92-e17d-4c4b-a275-0ed1a70532cf)

I did a quick edit and it would probably look something like this? And there would be a search box somewhere
![better-logs-2](https://github.com/modrinth/theseus/assets/97033682/dd0f0922-81fb-4028-8482-8427dea2b5ed)
ㅤ
ㅤ
**- Add the ability to send commands through the log window**
I don't know about you, but it seems like a cool feature if we could send commands to the chat using the log window, it kinda looks like a console window so why not just add the feature? (Of course I need to have the permission to run the command
![console](https://github.com/modrinth/theseus/assets/97033682/fe360fb1-6ef7-4bcb-8a30-ed900e96d678)
ㅤ
**- Add the ability to view crash reports from the Modrinth app**
Sometimes the logs don't show the crash report at all which would be the most important feature of "Logs" anyways.
So why not add a way to view crash reports from the app.
ㅤ
ㅤ
ㅤ
## 🔧Better mods updating system

- Mods that have an update will show on the top of the modlist
The update button that we have right now doesn't really look like an "Update" button 
![image](https://github.com/modrinth/theseus/assets/97033682/dbe31c9d-c541-4c1f-bbdb-aca2bdb4b04a)

- Well the image above might look something like an update button, but something like the picture below would look much more self-explanatory and convenient, and especially because CurseForge uses an update button that looks like the picture below, it would be easier for CurseForge users to use this launcher 😉
![image](https://github.com/modrinth/theseus/assets/97033682/af9462e8-2a4d-4871-95bb-9f77104e0a73)

- Also the update button should not be in the middle of a "deletion" button and a "enable/disable" button, because it is easy to just miss click the deletion button.
![image](https://github.com/modrinth/theseus/assets/97033682/697464fb-1c59-4a5d-931d-b3fd3f830821)
So please make it look like an actual update button, and make it the leftmost button 👍
ㅤ
ㅤ
ㅤ
## ⚠️Warning icons
- Mods that are for a different mod loader would have this warning icon next to them 
![incompatible-modloader](https://github.com/modrinth/theseus/assets/97033682/c030bf5e-5808-4164-ad74-06ac47ffb4b0)

- Mods that are detected to be incompatible with your modpack will have this icon next to them
(Basically this would require you guys to make some kind of system that would check for known incompatibilities in your modpack, which is kinda already implemented on the Modrinth website)
![crash-alert](https://github.com/modrinth/theseus/assets/97033682/e7cbfbff-270b-4cb5-8943-f21fdde2a527)

- Mods that are for older versions of Minecraft will have this icon next to them
![old-version-warning](https://github.com/modrinth/theseus/assets/97033682/a950698c-8e8c-4492-a5da-5cd3d27e8f99)
ㅤ
ㅤ
ㅤ
## 🪄 Tweaks
- Add an option to the Modrinth app config to disable this feature where I have **multiple pages of mods** in my modpack.

![modlist](https://github.com/modrinth/theseus/assets/97033682/c613232b-ceb8-4ea4-a53a-e13a7244a1a0)

I am used to scrolling a lot in my modpack mod lists, and I find it a little quicker and natural to just have _one_ list of mods in my modpacks 👍
But the best way to correct this problem that I and some other people also have it to just make an option for it.
ㅤ
ㅤ
ㅤ
### That's all of my ideas there, hope you liked them and would consider implementing even one of these features to the Modrinth app ❤️😉

**Comment by TheAlan404** [comment]
> Add the ability to send commands through the log window

impossible without modding the game since thats only a dedicated server feature

**Comment by User4716** [comment]
> > Add the ability to send commands through the log window
> 
> impossible without modding the game since thats only a dedicated server feature

I thought that it was impossible, but I decided to let you guys know that I still had the idea👍

**Comment by Felix14-v2** [comment]
> > Add the ability to send commands through the log window
> 
> impossible without modding the game since thats only a dedicated server feature

I think this will be amazing feature when Modrinth supports running dedicated servers

**Comment by triphora** [comment]
Please create separate issues for separate suggestions

**Comment by triphora** [comment]
Closing as it has been over a month since I requested this be split. If your suggestions are not yet implemented, please create a **separate, unique issue for each** and check for duplicates.
