### ISSUE TITLE
startup thing

### ISSUE THREAD

**Issue by S0apyy** [modrinth/theseus#601]
### Is your suggested enhancement related to a problem? Please describe.

the startup animation and sound can be very annoying to some people who just want to start the app and start a modpack.

### Describe the solution you'd like

an option to disable it in the options, or just remove it entirely

**Comment by thesuzerain** [comment]
As of the latest version, since this issue here, once the tutorial is complete, the startup animation no longer plays. Please reopen this as a bug if this is not the case for you on the latest version.
