### ISSUE TITLE
Use device flow for game login.

### ISSUE THREAD

**Issue by heipiao233** [modrinth/theseus#602]
### Is your suggested enhancement related to a problem? Please describe.

We can see many questions about this:
![image](https://github.com/modrinth/theseus/assets/81846300/f4c80687-93a9-44d9-bd29-7b04fb7e64ef)
Somebody told me that is because the rate limit. So why not just use device flow?

### Describe the solution you'd like

Use device flow as a option without removing current login flow.

**Comment by Geometrically** [comment]
fixed
