### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Trard** [modrinth/theseus#603]
### Describe the bug

When I start the launcher, it shows an endless loading. I used Microsoft DevTools and found this error:
![image](https://github.com/modrinth/theseus/assets/68790724/39febf14-84d8-407f-aa16-47f56e2a4ed1)

### Steps to reproduce

It's kind of tricky here.

1. Download and install Theseus.
2. Log in to your Microsoft and Modrinth accounts. 
3. Unplug your PC when Theseus is running.
4. Plug in and turn on your PC.
5. Launch Theseus.
6. See endless loading.
![image](https://github.com/modrinth/theseus/assets/68790724/ef29e110-40f2-4a13-a9a4-bd893258da41)

Also, I tried to reinstall the launcher, but it goes the same way.
1. Reinstall Theseus.
2. Launch Theseus.
3. See endless loading.

### Expected behavior

Fast launcher loading

### Additional context

Also, I have experienced some troubles when logging in my Microsoft and Modrinth accounts, but I don't know if it is related.
Here is this error:

> An error occurred invalid args challenge for command login_pass: command login_pass missing required key challenge

I use Windows 10 Pro 22H2.
I downloaded _Modrinth App_0.5.1_x64_en-US.msi_ from https://modrinth.com/app

**Comment by qtchaos** [comment]
Uninstall the Modrinth App, then go to  `%APPDATA%/com.modrinth.theseus` and delete everything there. Finally reinstall the Modrinth App and it should work

**Comment by DefomCode** [comment]
after almost a year, the error still appears...
