### ISSUE TITLE
Running instances are not visible after closing the app

### ISSUE THREAD

**Issue by ghost** [modrinth/theseus#606]
### Describe the bug

Running instances are not visible after closing the app. I think it shoul be like in other launchers for exaple Prism that I have used before. 

### Steps to reproduce

1. Open Modrinth App
2. Run one or more instances
3. Close app
4. Run Modrinth App again 
5. No instances running is shown

### Expected behavior

1. Open Modrinth App
2. Run one or more instances
3. Close app
4. Run Modrinth App again
5. Instances that still running are shown in app

**Comment by thesuzerain** [comment]
Duplicate of #272
