### ISSUE TITLE
Allow players to add and update individual mods in modpacks

### ISSUE THREAD

**Issue by Brachistocronium** [modrinth/theseus#610]
### Is your suggested enhancement related to a problem? Please describe.

I use the Additive modpack to play vanilla Minecraft with optimization mods and custom configs already installed, and I always put some client-side mods mostly for aesthetic purposes and QOL. As I imported my instances from Prism, I was confused and thought that my client was bugged when I didn't see the "Actions" column in my instances.

![image](https://github.com/modrinth/theseus/assets/97134777/c421c5bb-df76-40ac-997a-f0a438d95f0e)

### Describe the solution you'd like

Add the Actions column to modpacks.
Either you can only update, delete, or disable your added mods to avoid problems with the modpack, or have a separate "advanced mode" setting to also edit the included mods in the modpack for advanced users.

![image](https://github.com/modrinth/theseus/assets/97134777/910c0d96-3a93-4de8-9e2b-dfdf3760e05f)

### Additional context

ATLauncher and Prism allow you to add individual mods in modpacks and even edit the ones included in the pack. An option like this would be a nice addition to the Modrinth app

**Comment by HyperSoop** [comment]
yeah i see no reason not to allow people to personally operate on the mods in a modpack, this current behaviour is kinda stupid.

**Comment by qtchaos** [comment]
Are you aware of the option to unpair an instance? This allows you to edit the mods in a modpack. I also created a [pull request](https://github.com/modrinth/theseus/pull/630) to add clearer indication that you need to unpair an instance to edit it.
![image](https://github.com/modrinth/theseus/assets/72168435/aa308f9d-5eac-4b8c-995a-26a2ecc6acd9)

**Comment by Brachistocronium** [comment]
Oh, I was not aware of that feature. Though, I am concerned about unpairing an instance, which seems to be permanent unless I make another instance and download the modpack again, because I cannot update the whole modpack itself when unpaired and miss out on the mod and config changes made by the modpack author; risking on breaking the instance when I blindly update them all manually to latest. (Such as when Sodium updated to 0.5.1 that could cause problems for mods)

I was so used to how ATLauncher and PrismLauncher handle modpack updates and I just update the mods I added myself.

**Comment by qtchaos** [comment]
Created a [discussion](https://discord.com/channels/734077874708938864/1142458259836522496) for this in the Modrinth Discord server.

**Comment by qtchaos** [comment]
Now fixed with the unlock feature.
