### ISSUE TITLE
Cannot log into Minecraft Account

### ISSUE THREAD

**Issue by espot07** [modrinth/theseus#611]
### Describe the bug

When clicking the login button and being taken to my browser, I click the email I want to use and give permission for Modrinth to access my account. It then gives me this error:
![Error - Modrinth and 5 more pages - Personal - Microsoft​ Edge 8_17_2023 1_04_23 PM](https://github.com/modrinth/theseus/assets/91640297/09a7a8b7-4f2a-4b4c-a974-3c77bc785333)
It then shows the same error within the Modrinth App in the bottom right-hand corner in red. I've tried restarting it and that doesn't work either.

### Steps to reproduce

1. Start Modrinth Launcher for the first time
2. Hit the log-in button for Microsoft
3. Select email and give permissions
4. There's an error!

### Additional context

I have no idea what could be going wrong here, maybe it's because I use multiple launchers on this computer? I've used the vanilla launcher, GDLauncher, and Prism Launcher so maybe it's conflicting with that?

**Comment by Norbiros** [comment]
I can reproduce this bug. Debug info:
```json
{"error":"In Bearer token flow: Response didn't contain valid bearer token. body: {\n \"path\" : \"/launcher/login\"\n}"}
```

**Comment by Dueris** [comment]
I can also reproduce this, I also get an error where I have to sign in again upon reopening theseus

**Comment by espot07** [comment]
I don't know why, but I could successfully log in today. It might be that Hydra local pull request that went through last night, as it did something to the login system. I'm going to keep this open though incase other people are still having this issue.

**Comment by Geometrically** [comment]
fixed with new login system
