### ISSUE TITLE
Improve modpack updating UX

### ISSUE THREAD

**Issue by HyperSoop** [modrinth/theseus#616]
### Is your suggested enhancement related to a problem? Please describe.

I tend to make alpha versions of my modpack for Minecraft snapshots, which users should not expect to be stable or compatible nor should they be updated to them without warning. Updating a modpack between minecraft versions is a destructive action (especially in this case) and shouldn't be allowed to happen in a single click.

### Describe the solution you'd like

Ideally, a dialog should be shown to a user by the "Update modpack" button, prompting them to select the modpack version to update to, where the default is never a version for a different Minecraft version than the instance is currently on and is preferrably a version marked as a release.

**Comment by Madis0** [comment]
Also #194

**Comment by Madis0** [comment]
This is present as of 0.5.4.
