### ISSUE TITLE
404 on trying to log-in

### ISSUE THREAD

**Issue by Schwerthecht** [modrinth/theseus#659]
### Describe the bug

If i try to sign in with a Microsoft Account and click on "log in" first nothing happens and shortly after an error message pops up "Websocket Error: HTTP Error: 404 Not Found".

![image](https://github.com/modrinth/theseus/assets/90722328/2c7a093a-3470-423d-bcee-a11fb9f53d6b)

![image](https://github.com/modrinth/theseus/assets/90722328/7dfc6be3-44a4-4623-bb20-392240bbb20d)

### Steps to reproduce

1. Log out from any currently signed in accounts (I can't test this with an account signed in, but probably it's the same issue)
2. click on Steve's Head / the account symbol
3. click on the "sign in" button next to "Not signed in"
4. the 404 Error will appear in the right bottom corner

### Expected behavior

Microsoft sign-in page opens / external window with sign-in opens?

**Comment by Nitrrine** [comment]
Can you show console logs? (Ctrl+Shift+I)

**Comment by Nitrrine** [comment]
Can you open a network tab?

**Comment by Schwerthecht** [comment]
![image](https://github.com/modrinth/theseus/assets/90722328/fd2c7fd2-03c7-4c40-a9d8-0dda6d1b7c0c)
![image](https://github.com/modrinth/theseus/assets/90722328/994b267d-31fe-4dbb-8877-b68a39420421)

**Comment by sh0tybumbati** [comment]
I have the exact same issue.
If it's relevant, I'm running it on Manjaro

**Comment by Nitrrine** [comment]
Are you using the latest version of the app?

**Comment by Schwerthecht** [comment]
I'm on Manjaro too, forgot to mention that, sorry. I am using the modrinth-app-bin from AUR (Arch-User-Repository), it seems to be Version 0.5.0 of the Modrinth App. Latest version is 0.5.2, so thats probably an issue. I'm using the binarie release, because the other one (modrinth-app) won't build, and I can't find the missing build tool 'pck-config'.

Will Modrinth add an official User Repo for Arch? Or what would be the correct way to install on an Arch based OS?
