### ISSUE TITLE
the  issue with modrinth it wont let me sign in on my minecraft account

### ISSUE THREAD

**Issue by GodUmbreon** [modrinth/theseus#660]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/142951121/f11dd91a-72bf-4fe6-994f-f771ef01fbd6)
![image](https://github.com/modrinth/theseus/assets/142951121/0684a4dc-c27a-4741-80f9-9b4d721fd303)

### Steps to reproduce

1. account picture click the sign in 
2. putin my ursname 

### Additional context

i type in everything correct and i get this message 
An error occurred
Minecraft authentication Hydra error: No Minecraft account for profile. Make sure you own the game and have set a username through the official Minecraft launcher.

**Comment by xameryn** [comment]
Ran into the same issue, my problem was I was signed into my PC's Microsoft account at [https://account.microsoft.com/](https://account.microsoft.com/), not my Minecraft account, make sure you're signed into the account that you own Minecraft under, that fixed it for me.

**Comment by thesuzerain** [comment]
See above message. ^
The account you signed in with doesn't have a minecraft account attached to it- make sure you are using that correct one ! If you can confirm they are the same, please reopen

**Comment by thesuzerain** [comment]
See above message. ^
The account you signed in with doesn't have a minecraft account attached to it- make sure you are using that correct one ! If you can confirm they are the same, please reopen
