### ISSUE TITLE
App doesn't boot

### ISSUE THREAD

**Issue by Curus1971** [modrinth/theseus#662]
### Describe the bug

The modrinth app stays on the loading screen and won't boot

### Steps to reproduce

1. open the app
2. wait
3. still on loading screen

### Expected behavior

the app is supposed to boot

**Comment by thesuzerain** [comment]
Hi, can you please also post:
- your OS
- whether you are connected to the internet
- whether this happens consistently, even after a computer restart, etc
- any logs you have in the /modrinth_logs/ section
- any errors in the console (depending on your OS, there are different shortcuts to open the web development console)
Thanks !

**Comment by Durst-xx** [comment]
I just began experiencing this issue as well today after a computer hard-freeze and forced restart.

- Windows 10
- I am connected to the internet
- I have restarted normally several times and the issue persists
- There are no log files
- There was an anonymous object error on the console

I also tried uninstalling then reinstalling the launcher without success. 

Additionally,  while the spinning logo is showing, 100% CPU is being used until I force close the launcher.

**Comment by thesuzerain** [comment]
There 

> I just began experiencing this issue as well today after a computer hard-freeze and forced restart.
> 
> * Windows 10
> * I am connected to the internet
> * I have restarted normally several times and the issue persists
> * There are no log files
> * There was an anonymous object error on the console
> 
> I also tried uninstalling then reinstalling the launcher without success.
> 
> Additionally, while the spinning logo is showing, 100% CPU is being used until I force close the launcher.

Thanks! Yours was working in the past though? Is there no files in Roaming\com.modrinth.theseus\launcher_logs or does the folder not exist at all?

**Comment by Durst-xx** [comment]
Found the log! Thanks for your help.

2023-09-01T15:43:54.920058600-04:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-09-01T15:43:55.730021500-04:00 ERROR theseus_gui::error: error=Serialization error (JSON): expected value at line 1 column 1 span_trace=   0: theseus::state::settings::init
           with file="C:\\Users\\...\\AppData\\Roaming\\com.modrinth.theseus\\settings.json"
             at theseus\src\state\settings.rs:50
   1: theseus::state::initialize_state
             at theseus\src\state\mod.rs:130

**Comment by Durst-xx** [comment]
Deleting that file seems to have worked. Guessing it was corrupted.

**Comment by thesuzerain** [comment]
awesome thanks. This is part of a bug that will be fixed!

**Comment by Durst-xx** [comment]
Wonderful!! A big thank you for the quick action!

**Comment by Curus1971** [comment]
i am on windows eleven and deleting the log file did nothing

**Comment by thesuzerain** [comment]
The log file is not the corrupt one. 

> i am on windows eleven and deleting the log file did nothing

The log file is not the corrupt one, the file that the log says it could not load is the. corrupt one. It's probably settings.json or caches/metadata/tags.json or caches/metadata/metadata.json

**Comment by Curus1971** [comment]
thank you
