### ISSUE TITLE
Add any Discord RPC controls

### ISSUE THREAD

**Issue by NikSneMC** [modrinth/theseus#666]
### Is your suggested enhancement related to a problem? Please describe.

Many mods have their own RPC that can be disabled. Some loaders are detected by Discord automatically. But the application's RPC overrides all custom other (I haven't tested Discord detection). And activity is Modrinth, not Minecraft. You can't disable it for launcher or instances.

### Describe the solution you'd like

Add switches for RPC to the launcher and profile settings. The first one only works when no profile is running.

### Additional context

Add settings for RPC fields
It would be cool: Images. Custom image, profile picture (large image only), player head or default image
It would be very cool: add the ability to provide a custom RPC application ID

_No response_

**Comment by Tom60chat** [comment]
At least somethings to disable it globally (and possible for each modpacks), would be nice.

**Comment by NikSneMC** [comment]
> At least something to disable it globally (and possibly for each modpack) would be nice.

I think that we have issues about it

**Comment by thesuzerain** [comment]
Globally will be the first option. We will perhaps look into customizing for the future

**Comment by NikSneMC** [comment]
> Globally will be the first option. We will perhaps look into customizing for the future

Thanks!
