### ISSUE TITLE
Texture Packs are apparently "Mods"

### ISSUE THREAD

**Issue by RealmKebab** [modrinth/theseus#696]
### Describe the bug

So, texture packs appear on the mods tab even though it isn't a mod and is just a simple texture pack.

### Steps to reproduce

1. Install a texturepack
2. Drag it into your texturepack directory
3. Check the mods tab

### Expected behavior

It not be shown on the mods tab

### Additional context

![image](https://github.com/modrinth/theseus/assets/73048123/2c05f0d8-803c-43e4-82c5-4af053fb2ad9)

The one with some enchanted type of gibberish at the top is a texturepack

(also the texturepack directory when clicked in-game just brings up an error)

**Comment by Enderteck** [comment]
This is intentional

if you wanna disable it change the show button to mods like this
![Screenshot](https://github.com/modrinth/theseus/assets/123917079/92b89412-6dda-4ae3-bae8-00f55a988b09)

**Comment by Poopooracoocoo** [comment]
Could "mods" in the sidebar be renamed to something like "content" or "add-ons" to fix this?

**Comment by Enderteck** [comment]
> Could "mods" in the sidebar be renamed to something like "content" or "add-ons" to fix this?

What do you mean

**Comment by Poopooracoocoo** [comment]
![264402593-2c05f0d8-803c-43e4-82c5-4af053fb2ad9](https://github.com/modrinth/theseus/assets/51363864/ff8e2496-73e0-46e2-ac7d-dfab6b43376e)
Renaming it to "Content" would make it consistent with the "Add content" button

**Comment by Enderteck** [comment]
> > > Could "mods" in the sidebar be renamed to something like "content" or "add-ons" to fix this?
> > 
> > What do you mean
> 
> @Enderteck 
> ![264402593-2c05f0d8-803c-43e4-82c5-4af053fb2ad9](https://github.com/modrinth/theseus/assets/51363864/ff8e2496-73e0-46e2-ac7d-dfab6b43376e)
> Renaming it to "Content" would make it consistent with the "Add content" button 

I think that it should match with what is shown in the content list.
