### ISSUE TITLE
Modrinth app refuses load 

### ISSUE THREAD

**Issue by a-person1908** [modrinth/theseus#708]
### Describe the bug

It just refuses to load, its been over 7-8 minutes and hasn't seemed to do litteraly anything, it is not my hardware as other apps work correctly.

### Steps to reproduce

I am not entirly sure but I belive it was caused by a GPU crash under stress.

### Expected behavior

The app usually launches within a few seconds to around 13 seconds max.

### Additional context

GPU crashed during stress while the modrinth app was open and no longer works, it seems to be in a crash like state, only closing after use of task manager not even ALT-F4.

**Comment by RealRomanFiend** [comment]
i am also having this same problem. when i woke up, the app just stopped working. it was working fine yesterday too

**Comment by a-person1908** [comment]
Update: just un-installed and re installed it, still won't load

**Comment by RealRomanFiend** [comment]
@a-person1908 i have found a solution thanks to @Geometrically 

Delete %APPDATA%\com.modrinth.theseus

this worked for me, i hope it works for as well.

**Comment by a-person1908** [comment]
aw man that would delete my minecraft save data

**Comment by RealRomanFiend** [comment]
yea unfortunately... you can probably save stuff like xaeros worldmap file tho

**Comment by thesuzerain** [comment]
You likely do not need to delete everything in that folder if you are doing that!!!
I would recommend deletting settings.json, as well as the files caches/metadata (in particular, tags.json and metadata.json)

**Comment by a-person1908** [comment]
tryna fix my settings file only to find this: 
![image](https://github.com/modrinth/theseus/assets/137985347/89623acc-10db-49d3-b90f-16a8d92860a4)

**Comment by a-person1908** [comment]
I love it when basic config files are encoded, its so fun

**Comment by a-person1908** [comment]
'-' ITS ALL A SINGLE UNICODE CHARACTER

**Comment by thesuzerain** [comment]
Seems like it was corrupted when the crash happened as the file was being written to. The settings.json is not designed to be encoded, it's just a json text file. We are looking into a backup system/sled db/etc. If you just delete it from the folder, does it regenerate?

**Comment by a-person1908** [comment]
Update: the file was just super corrupted completly

**Comment by a-person1908** [comment]
dam
