### ISSUE TITLE
[Bug] Creating new instance fails when selecting NeoForge

### ISSUE THREAD

**Issue by ApexModder** [modrinth/theseus#715]
### Describe the bug

When trying to create a new instance and selecting NeoForge as the ModLoader an error is encountered stating that NeoForge is an unknown loader variant.

### Steps to reproduce

1. Create new instance
2. Select NeoForge as ModLoader
3. Click green create button

### Expected behavior

Expected a new instance to be created using NeoForge as the ModLoader.

### Additional context

![image](https://github.com/modrinth/theseus/assets/29412632/3f3a3249-5358-45a2-bd9f-3ec9e5305f4d)

![image](https://github.com/modrinth/theseus/assets/29412632/0177a57d-3c43-43f9-b12f-69ae474d0a97)

**Comment by Renceron** [comment]
it was: it was

**Comment by thesuzerain** [comment]
Duplicate of #702
