### ISSUE TITLE
Unable to launch older versions of Minecraft

### ISSUE THREAD

**Issue by IkeVoodoo** [modrinth/theseus#722]
### Describe the bug

Attempting to launch a vanilla profile on 1.8.9 instantly terminates with

```
Error during initialization of VM
Could not reserve enough space for 2097152KB object heap
```

### Steps to reproduce

1. Create a new Vanilla profile on version 1.8.9
2. Wait for installation
3. Start the profile
4. View the profile and check logs

### Expected behavior

I expected the 1.8.9 profile to start, and later open a game window.

### Additional context

I have only tried 1.8.9 and 1.8, though this is likely present in other versions as well.

**Comment by triphora** [comment]
This is an out of memory error, not a bug; join us on https://discord.gg/modrinth for support

**Comment by IkeVoodoo** [comment]
Oh I just read the amount wrong, thought it tried to allocate 20GB instead of 2GB, my bad!
