### ISSUE TITLE
Supported Platforms

### ISSUE THREAD

**Issue by thecatcore** [modrinth/theseus#73]
Which Platforms and architectures will be supported by the gui and the cli?

**Comment by triphora** [comment]
Windows, Mac, Linux (probably Flatpak and/or AppImage initially with distro-specific packaging coming later)

x86_64 and aarch64/ARM64 (we've been testing very extensively with M-series Macs to be specific)

These are what we're looking for when it comes to the minimum we can launch with. If there is demand for it we are able to expand to other platforms and arches as well.

**Comment by arthurbambou** [comment]
Will there be any extra support for arm64 for mc versions that didn't officially support it?

**Comment by Geometrically** [comment]
> Will there be any extra support for arm64 for mc versions that didn't officially support it?

yes

**Comment by Danik1601** [comment]
> Windows, Mac, Linux (probably Flatpak and/or AppImage initially with distro-specific packaging coming later)

Flatpak and AppImage are always welcome!

**Comment by arthurbambou** [comment]
Probably only x86_64 and arm64 for now as that's the only architectures tauri supports rn. Probably the cli can be made to work where tauri can't handle it? Only if the cli is worked on tho.

**Comment by BlueZeeKing** [comment]
I have an M1 Mac that I could use to test anything that needs it

**Comment by Geometrically** [comment]
windows x86/arm, linux x86/arm, macos x86/arm
