### ISSUE TITLE
A "Update all mods" button.

### ISSUE THREAD

**Issue by MIfoodie** [modrinth/theseus#732]
### Is your suggested enhancement related to a problem? Please describe.

Does someone have any good reason why I have to go through all of my 9 pages of mods just to find that one mod that needs to be updated?

### Describe alternatives you've considered

Bring all mods that could be updated to the top of the list.

**Comment by thesuzerain** [comment]
You should be able to click the checkbox that checks all the mods and and a mass update button should appear- Does that work?

**Comment by Prospector** [comment]
hmm, this issue brings up a good point, now that there is pagination if it selects all items even on other pages, that is kinda unexpected behavior

**Comment by thesuzerain** [comment]
Yeah that’s true. Either way there should be an explicit update all in next patch

**Comment by MIfoodie** [comment]
> You should be able to click the checkbox that checks all the mods and and a mass update button should appear- Does that work?

oh wow I didn't realize that. I guess if I didn't realize this then I'm not the only one then...

**Comment by thesuzerain** [comment]
will be added in next update
