### ISSUE TITLE
Imported mrpack instance says "error fetching project"

### ISSUE THREAD

**Issue by jriesen** [modrinth/theseus#747]
Since updating to v0.5.4, any mrpack that I have imported (even ones imported _before_ upgrading) now throw up "An error occurred" "Error fetching project" in the bottom whenever I select that instance in my library. There do not seem to be any other problems otherwise with the instance. This only occurs with modpacks that are not from the Modrinth website, e.g. ones I have created myself within Modrinth App and exported for friends.

Digging through code it looks like the issue is almost certainly [this addition](https://github.com/modrinth/theseus/commit/1e8852b54007f8739d94c4593aa369ac512b30fc#diff-5d8adfd5edf7d0c7a8b8593cbf78f6a515e23581298b74e5948e0029ecb4fd9fR204) added in #703.  I suspect that imported mrpacks set some stub data in `linked_data` and then sending a request for `https://api.modrinth.com/v2/project/${instance.value.metadata.linked_data.project_id}/version` when there is no `project_id` for my homemade and never-uploaded mrpack is almost certainly the culprit.

**Comment by Voidlighter** [comment]
I think this problem may be why I'm unable to unpair the instance, rename it, or otherwise edit it. Everything else appears to work fine, but it's a static instance.
