### ISSUE TITLE
Bug: Modrinth app exports shaderpacks and unwanted mods despite explicitly unchecking them during export.

### ISSUE THREAD

**Issue by TheD0ct0r101** [modrinth/theseus#754]
I'm hoping its not just me experiencing this, but basically in the window where it allows me to select what folders/files I am exporting to a .mrpack file, I would uncheck the shaderpack folder as well as any clientside mods I dont feel need to be in the official modpack release. However upon uploading the .mrpack to modrinth, those shaderpacks/mods that I unchecked during the export process are just there in the file anyway.

**Comment by TheD0ct0r101** [comment]
To clarify, the window is worded like this: 
![image](https://github.com/modrinth/theseus/assets/11579139/767551ce-a5f3-43e6-b99d-659cf0951ffa)

unchecking a folder should exclude it from being included in the export entirely, full-stop. But weirdly this doesnt seem to be the case with unchecking shaderpacks or individual mods.

**Comment by GeraldTM** [comment]
yes, as far is I'm aware, this checkbox is for specifying files not hosted on modrinth, or specific files (eg configs) you want to be installed for the user. them mods themselves are not shipped out directly in the pack, but a link of sorts is stored in the modrinth.index.json
