### ISSUE TITLE
Launching an instance with out of date mods crashes instead of disabling the mod

### ISSUE THREAD

**Issue by slushie0** [modrinth/theseus#784]
### Describe the bug

If I have a 1.20.1 fabric instance with the ESSENTIAL mod installed, and update that instance to 1.20.2 and launch the game, it will crash since essential is no available for 1.20.2 yet. The launcher should automatically disable all out of date mods and make it easy to see them in a new list.

### Steps to reproduce

Create a new fabric 1.20.2 instance
install ESSENTIAL mod on that instance
launch the game
update that instance to 1.20.2
launch game again
the game crashes since ESSENTIAL is out of date

### Expected behavior

Instead of crashing, the launcher should detect all out of date mods and flag them as outdated, and add them to a new list of outdated mods.

### System information

Fedora Linux

**Comment by triphora** [comment]
This is not a bug. The app can't tell what your intentions are, and many mods work across versions, even if they are not marked to. If you want to file a *suggestion* or *enhancement*, please do, but this is not a *bug*.
