### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by jucogjucogi** [modrinth/theseus#817]
### Is your suggested enhancement related to a problem? Please describe.

I want an option to disable launcher RPC, because I want to customize the presence, that's why I install CraftPresence.

### Describe the solution you'd like

Add an option to disable discord presence.

### Describe alternatives you've considered

Just closing the app, but it's not comfortable.

**Comment by ToBinio** [comment]
Isn't that what this toggle in the settings does?
![grafik](https://github.com/modrinth/theseus/assets/81473300/dbb20d8d-d57f-4421-8dfd-b5fc94aba014)

**Comment by triphora** [comment]
See above
