### ISSUE TITLE
Failure to run the Create: Above and Beyond modpack

### ISSUE THREAD

**Issue by ananthashesha3000** [modrinth/theseus#823]
### Describe the bug

Every time I try to launch the modpack, it fails to do so and shows the error messages "Error launching Minecraft: Java path invalid or non-functional: C:\Program Files (x86)\Common Files\Oracle\Java\javapath_target_" and "Minecraft authentication Hydra error: No Minecraft account for your profile. Make sure you own the game and have set a username through the official Minecraft launcher."

### Steps to reproduce

1. Download the Create: Above and Beyond modpack on Forge (app or website)
2. Add Optifine to the mod list
3. Import the modpack to the Modrinth app
4. Try to run it
5. Fail to run it

### Expected behavior

I expected the game to run normally, or at least crash later on.

### System information

I run this on Windows 10, and the version of the app is the latest at the time of writing, which is the 21st of October 2023

### Additional context

[Forge 1.16.5 Client Log [#PLkf1Bw]](https://mclo.gs/WEzWQVE)

**Comment by Sahnetorte07** [comment]
i had the same error message in a different situation, but i fixed it by heading into the modrinth settings and installing the recommended java versions in the java setting section. So maybe that fixes yours too

**Comment by triphora** [comment]
See the above message.
