### ISSUE TITLE
Disable Default Discord Rich Presence

### ISSUE THREAD

**Issue by DAMIANOO9** [modrinth/theseus#842]
### Is your suggested enhancement related to a problem? Please describe.

It's kinda annoying when I have custom mods for rich presence but the modrinth one gets in the way.

### Describe the solution you'd like

A setting (preferably per profile but any will do) that will make the modrinth rich presence not appear.

**Comment by ToBinio** [comment]
Isn't this the same as #817?

**Comment by DAMIANOO9** [comment]
> Isn't this the same as #817?

Sorry, didn't notice
