### ISSUE TITLE
Latest fabric version not displayed

### ISSUE THREAD

**Issue by OrbitalExplorer** [modrinth/theseus#855]
### Describe the bug

see title

### Steps to reproduce

manage or create new modrinth instance
try to change loader version
see latest option is 0.14.23
Go to fabricmc.net
download installer
see latest version is 0.14.24

### Expected behavior

see version 0.14.24

### System information

Windows 11

### Additional context

![image](https://github.com/modrinth/theseus/assets/75388592/fe46ddc2-eb28-4f99-8e7d-9327469117e6)
![image](https://github.com/modrinth/theseus/assets/75388592/99dd2400-a049-43bd-b06d-fca7f2468245)

**Comment by triphora** [comment]
Scroll down, it's a known bug that's already fixed locally and doesn't actually have anything to do with theseus.
