### ISSUE TITLE
Unable to disable F7 permanently

### ISSUE THREAD

**Issue by Felix14-v2** [modrinth/theseus#893]
### Description

After pressing F7, Theseus prompts you to enable keyboard text cursor navigation, and it doesn't matter if you have disabled this behavior by ticking "don't show again" and closing the notification.

### To reproduce

1. Open the launcher
2. Press F7
3. Tick "don't show again" and press "cancel"
4. Press F7 again
5. See the result

### Expected behavior

Theseus shouldn't respond to F7 at all.

### System information

- Windows 11
- Theseus 0.6.1

### Additional

https://github.com/modrinth/theseus/assets/75726196/9155cb24-f6f6-4764-804a-59bd010eca2b

**Comment by wlad26** [comment]
It's not a Theseus bug since it uses MSEdgeWebview2 and this function is provided by Edge
You can open Edge and see the same pop-up behavior
And I don't think this pattern may be even called as a bug

**Comment by Felix14-v2** [comment]
> You can open Edge and see the same pop-up behavior
> And I don't think this pattern may be even called as a bug

I tested it in Edge too, but this buggy behaviour occurs only in launcher

**Comment by wlad26** [comment]
I checked once again and in both programs this function works properly:

https://github.com/modrinth/theseus/assets/65756919/0b0a98f3-ada8-47c1-85b7-5b902f83cc3f


https://github.com/modrinth/theseus/assets/65756919/815cf36f-7788-43be-8fe0-0c8140c2940a

So, what's your problem about?

**Comment by Felix14-v2** [comment]
>  WindowsSandboxClient_lDxNfYA9IH.mp4 
> So, what's your problem about?

Sorry, but I can't translate this into English properly, so I'll write in my native. Тем более, что ты его понимаешь.
<details>
 <summary></summary>
Ты продемонстрировал точно ту же проблему, что я описывал выше – при нажатии галки "больше не показывать" уведомление мало того, что продолжает показываться, так ещё и игнорирует то, что ты запретил лаунчеру включать режим активного курсора по нажатию F7.  Причём сделал это 4 (!) раза, и ни на один из них лаунчер не отреагировал корректно. И, судя по всему, по итогу он просто скрыл уведомление, при этом не заблокировав активацию режима активного курсора. Хотя нажатие кнопки "не показывать снова" с последующим закрытием уведомления активации режима должна отключать (и отключает в нормальных браузерах) эту функцию навсегда.
</details>

**Comment by wlad26** [comment]
Sorry for using Russian, but it's more convenient to use in this thread
> Хотя нажатие кнопки "не показывать снова" с последующим закрытием уведомления активации режима должна отключать (и отключает в нормальных браузерах) эту функцию навсегда.

Я понимаю, что тебя не устраивает такой паттерн поведения клавишной навигации (то есть, что поп-ап продолжает всплывать даже при нажатии "Больше не спрашивать"), но:
"Больше не спрашивать" (Don't ask me) == "Больше не показывать всплывающее окно" (Turn on immediately)
Этот чекбокс напрямую говорит  только о том, что при его нажатии и последующих включениях функции она включится сразу без всплывающего окна, он **не говорит** о запрете на использование функции

Вот пример чекбокса, который напрямую говорит о том, что он разрешает/запрещает использование советов:
![soffice bin_rTO3gkoiLx](https://github.com/modrinth/theseus/assets/65756919/2c21b0c7-ea49-44dc-a9af-f0bf0e4ac284)

Поэтому:
1. Тебе нужно закрыть этот багрепорт, потому что проблема относится к Edge, а не Modrinth
2. Если тебе не нравится такой паттерн поведения, напиши в поддержку Edge или на их форум
3. В каком нормальном браузере эта галочка навсегда отключает поп-ап?

**Comment by triphora** [comment]
Closing per above
