### ISSUE TITLE
New 0.6.3 Appimage does not launch on Kubuntu 22.04.3

### ISSUE THREAD

**Issue by noah-pm-dev** [modrinth/theseus#944]
### Describe the bug

When trying to run the appimage, app immediately crashes with the following error:
```
[/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.1/src/linux.rs:104] buffer = ""
```

### Steps to reproduce

1. Download most recent appimage release
2. Make executable with `sudo chmod +x modrinth-app_0.6.3_amd64.appimage`
3. Run appimage with `./modrinth-app_0.6.3_amd64.appimage`

### Expected behavior

The app should launch

### System information

Kubuntu 22.04.3 LTS x86_64 | X11
DE: Plasma 5.24.7

### Additional context

Previous appimagae release launched normally.

**Comment by noah-pm-dev** [comment]
Issue somehow resolved itself, unsure how.

**Comment by catvin82** [comment]
having a similar problem to me at issue #981
