### ISSUE TITLE
Organization accounts appearing as null

### ISSUE THREAD

**Issue by UpcraftLP** [modrinth/theseus#989]
### Describe the bug

Organization accounts appear as empty text in the mod list UI, and display `null` on hover (see screenshot).

![image](https://github.com/modrinth/theseus/assets/10714589/db120fd0-2017-4907-82ec-91a05294c946)

### Steps to reproduce

1. view any mod owned by an organization account

### Expected behavior

The organization name is displayed correctly

### System information

Windows 10

**Comment by triphora** [comment]
Duplicate of #982
